// Generated by tools/storage_schema.rb; edit protocol/unsettled.sql.
enum ReplicaUnsettledSQL {
    static let sql = """
    -- Every local write still relevant, accepted ones included until a round shows them.
    -- Each row is decoded individually by the adapter.
    SELECT CAST(payload AS BLOB) FROM intents;
    """
}
