// Generated by tools/storage_schema.rb; edit protocol/storage.sql.
enum ReplicaSyncSchema {
    static let sql = """
    -- The whole client store, format 3 (`PRAGMA user_version = 3`). Native adapters
    -- own the transactions and the declared read indexes over `snapshots`.
    
    -- The store's identity, what it synchronizes, and its local settings.
    -- `next_sequence` orders frozen submissions; the server knows operations by UUID.
    CREATE TABLE IF NOT EXISTS meta (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        store_id TEXT NOT NULL,
        namespace TEXT,
        schema_version INTEGER,
        dataset TEXT,
        next_sequence INTEGER NOT NULL DEFAULT 1,
        document_mode TEXT CHECK (document_mode IN ('replicated', 'projections')),
        adopted_from INTEGER,
        adopted_to INTEGER,
        adopted_store_id TEXT
    );
    
    -- What application reads see: the base with local work rebased over it.
    CREATE TABLE IF NOT EXISTS snapshots (
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        shard TEXT NOT NULL,
        type TEXT,
        data TEXT,
        PRIMARY KEY (stream, row_id)
    );
    
    CREATE TABLE IF NOT EXISTS docs (
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        shard TEXT NOT NULL,
        codec TEXT NOT NULL,
        fold BLOB NOT NULL,
        acked BLOB,
        peer INTEGER NOT NULL,
        revision INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (stream, row_id)
    );
    
    CREATE TABLE IF NOT EXISTS stream_meta (
        stream TEXT PRIMARY KEY,
        change_seq INTEGER NOT NULL DEFAULT 0
    );
    
    -- An address's current lifetime. It outlives a deleted row, so a deliberate
    -- recreation can name the lifetime it replaces.
    CREATE TABLE IF NOT EXISTS entities (
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        shard TEXT NOT NULL,
        incarnation TEXT NOT NULL,
        predecessor TEXT,
        PRIMARY KEY (stream, row_id)
    );
    
    -- Reference lifetimes belong to local intent, including work held by sync gates.
    CREATE TABLE IF NOT EXISTS entity_references (
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        name TEXT NOT NULL,
        target_stream TEXT NOT NULL,
        target_id TEXT NOT NULL,
        target_incarnation TEXT NOT NULL,
        PRIMARY KEY (stream, row_id, name),
        FOREIGN KEY (stream, row_id) REFERENCES entities(stream, row_id) ON DELETE CASCADE
    );
    
    -- The server's rows as last published, sealed by `integrity`.
    CREATE TABLE IF NOT EXISTS base (
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        shard TEXT NOT NULL,
        incarnation TEXT NOT NULL,
        revision INTEGER NOT NULL,
        type TEXT,
        data TEXT NOT NULL,
        codec TEXT,
        fold BLOB,
        integrity TEXT,
        PRIMARY KEY (stream, row_id)
    );
    
    -- Per shard: the cursor of the last published round, and a generation that a
    -- reset bumps so an answer already on the wire cannot publish into it.
    CREATE TABLE IF NOT EXISTS checkpoints (
        shard TEXT PRIMARY KEY,
        cursor TEXT,
        generation INTEGER NOT NULL DEFAULT 0
    );
    
    -- A pull round in progress: the cursor to continue from, whether it started
    -- without one, and the highest accepted submission sequence when it started.
    CREATE TABLE IF NOT EXISTS downloads (
        shard TEXT PRIMARY KEY,
        cursor TEXT,
        reset INTEGER NOT NULL,
        visible INTEGER NOT NULL,
        started_at REAL NOT NULL
    );
    
    CREATE TABLE IF NOT EXISTS download_pages (
        shard TEXT NOT NULL,
        page INTEGER NOT NULL,
        content BLOB NOT NULL,
        PRIMARY KEY (shard, page)
    );
    
    -- Every local write the server is owed or has answered; rowid is drain order.
    -- draft: waits for its draft to commit. owed: editable, not yet sent.
    -- frozen: its bytes are in `submissions` under `operation`. accepted: stays
    -- visible until a round that started after `sequence` publishes.
    -- refused: kept with the server's reason until the application dismisses it.
    CREATE TABLE IF NOT EXISTS intents (
        id TEXT PRIMARY KEY,
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('draft', 'owed', 'frozen', 'accepted', 'refused')),
        op TEXT NOT NULL,
        payload TEXT NOT NULL,
        preimage TEXT,
        lane TEXT NOT NULL DEFAULT 'bulk',
        draft TEXT CHECK ((state = 'draft') = (draft IS NOT NULL)),
        sequence INTEGER CHECK ((state IN ('frozen', 'accepted')) = (sequence IS NOT NULL)),
        operation TEXT UNIQUE CHECK ((state = 'frozen') = (operation IS NOT NULL)),
        reason TEXT CHECK ((state = 'refused') = (reason IS NOT NULL)),
        created_at REAL NOT NULL
    );
    CREATE INDEX IF NOT EXISTS intents_address ON intents(row_id, stream);
    CREATE INDEX IF NOT EXISTS intents_owed ON intents(lane) WHERE state = 'owed';
    CREATE INDEX IF NOT EXISTS intents_draft ON intents(draft, row_id) WHERE state = 'draft';
    CREATE INDEX IF NOT EXISTS intents_sequence ON intents(sequence) WHERE sequence IS NOT NULL;
    
    -- Frozen wire operations, sent byte for byte on every retry until answered.
    CREATE TABLE IF NOT EXISTS submissions (
        sequence INTEGER PRIMARY KEY,
        content BLOB NOT NULL
    );
    
    -- A row a sync gate holds: its writes stay local until the gate lets it go.
    -- `seq` is the order of the first hold, the release order, parent before child.
    -- `server_knows`: the birth was sent before the hold, so it leaves as a patch.
    CREATE TABLE IF NOT EXISTS holds (
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        gate_id TEXT NOT NULL,
        reason TEXT NOT NULL,
        seq INTEGER NOT NULL,
        server_knows INTEGER NOT NULL,
        preimage BLOB NOT NULL,
        PRIMARY KEY (stream, row_id)
    );
    CREATE INDEX IF NOT EXISTS holds_by_gate ON holds(gate_id, seq);
    CREATE INDEX IF NOT EXISTS holds_by_row ON holds(row_id);
    
    CREATE TABLE IF NOT EXISTS recoveries (
        id TEXT PRIMARY KEY,
        stream TEXT NOT NULL,
        row_id TEXT NOT NULL,
        incarnation TEXT NOT NULL,
        reason TEXT NOT NULL,
        payload BLOB NOT NULL,
        created_at REAL NOT NULL
    );
    
    CREATE TABLE IF NOT EXISTS recovery_parts (
        recovery_id TEXT NOT NULL REFERENCES recoveries(id) ON DELETE CASCADE,
        kind TEXT NOT NULL,
        part_key TEXT NOT NULL,
        content BLOB NOT NULL,
        PRIMARY KEY (recovery_id, kind, part_key)
    );
    """
}
