// Generated by tools/storage_schema.rb; edit protocol/status.sql.
enum ReplicaStatusSQL {
    static let sql = """
    -- One read snapshot; aggregate in SQLite without materializing the backlog.
    SELECT
        (SELECT COUNT(*) FROM intents WHERE state = 'owed') AS queued,
        (SELECT COUNT(*) FROM holds) +
            (SELECT COUNT(DISTINCT draft) FROM intents WHERE state = 'draft') AS held,
        (SELECT COUNT(*) FROM submissions) AS submitted,
        (SELECT COUNT(*) FROM intents WHERE state = 'refused') AS rejected,
        (SELECT COUNT(*) FROM intents WHERE state = 'accepted') AS accepted,
        (SELECT COUNT(*) FROM recoveries) AS recovery,
        (SELECT MIN(created_at) FROM intents WHERE state <> 'accepted') AS oldest_intent,
        (SELECT MIN(started_at) FROM downloads) AS oldest_download,
        (SELECT COALESCE(SUM(length(CAST(payload AS BLOB))), 0) FROM intents WHERE state <> 'accepted') AS journal_bytes,
        (SELECT COALESCE(SUM(length(content)), 0) FROM submissions) AS submitted_bytes,
        (SELECT COALESCE(SUM(length(CAST(payload AS BLOB))), 0) FROM intents WHERE state = 'accepted') AS accepted_bytes,
        (SELECT COALESCE(SUM(length(content)), 0) FROM download_pages) AS download_bytes,
        (SELECT COALESCE(SUM(length(content)), 0) FROM recovery_parts) AS recovery_bytes,
        (SELECT COALESCE(SUM(length(fold)), 0) FROM docs) AS document_bytes;
    """
}
