// Generated by replica-codegen — DO NOT EDIT.
// Defaults for document stream `boards`.
//
// Swift spells these as `static let` constants; a Rust value that owns a
// `String` is not const-constructible, so they are associated functions.
// Every field is written out, exactly as the Swift literal does — nothing
// is filled in by `Default`.

use super::board_document::BoardDocumentMeta;

pub struct BoardDefaults;

impl BoardDefaults {
    pub fn meta() -> BoardDocumentMeta {
        BoardDocumentMeta {
            name: "Untitled".to_owned(),
        }
    }
}
