// Generated by replica-codegen — DO NOT EDIT.
// Document value for stream `boards` · codec loro@1
//
// Rust cannot nest a type inside a struct, so the Swift emitter's nesting
// path is flattened into one identifier with the ROOT stripped
// (`DeckDocument.Slide.Style.ShadowOffset` → `SlideStyleShadowOffset`),
// except `meta`, which every document may carry (`DeckDocument.Meta` →
// `DeckDocumentMeta`).
// Enum cases keep the emitter's spelling with the first character
// upper-cased; a leading underscore (a raw value that starts with a digit)
// survives (`_169`, `_43`, `sdr` → `Sdr`). Struct fields are snake_case,
// which is already the document lane's wire spelling, so no serde rename is
// needed here. `new(..)` takes the fields with NO declared default, in
// declaration order; a struct whose fields all have defaults also gets
// `Default`. Decoding runs through a private all-`Option` `Raw` mirror: a
// declared default fills a missing key, an enum VALUE this build does not
// know collapses to the field's declared default, and a required field still
// refuses — while a LIST of enums stays strict, because the derived
// `Deserialize` is what decodes it.
//
// BoardDocument owns generated values; ReplicaMan owns the live document.

use serde::de::Deserializer;
use serde::{Deserialize, Serialize};

use replicaman::document_value::DocumentFields;

#[derive(Clone, Debug, Default, PartialEq)]
pub struct BoardProjection {
    pub meta: DocumentFields,
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct BoardDocumentMeta {
    pub name: String,
}

impl BoardDocumentMeta {
    pub fn new() -> Self {
        Self {
            name: "Untitled".to_owned(),
        }
    }
}

impl Default for BoardDocumentMeta {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de> Deserialize<'de> for BoardDocumentMeta {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Raw {
            name: Option<String>,
        }

        let raw = Raw::deserialize(deserializer)?;

        Ok(BoardDocumentMeta {
            name: raw.name.unwrap_or_else(|| "Untitled".to_owned()),
        })
    }
}

impl BoardDocumentMeta {
    pub fn from_document_fields(fields: &DocumentFields) -> Option<Self> {
        coding::decode(fields)
    }

    pub fn document_fields(&self) -> DocumentFields {
        coding::encode(self, &Shape::object(vec![("name", Shape::String)]))
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoardDocument {
    pub meta: BoardDocumentMeta,
}

impl BoardDocument {
    pub fn new(meta: BoardDocumentMeta) -> Self {
        Self { meta }
    }

    /// Refuse a partial typed document: round-tripping it would discard
    /// undecodable registry entries. The caller retains the raw projection.
    pub fn from_projection(projection: &BoardProjection) -> Option<Self> {
        let meta = BoardDocumentMeta::from_document_fields(&projection.meta)?;

        Some(Self::new(meta))
    }

    pub fn projection(&self) -> BoardProjection {
        BoardProjection {
            meta: self.meta.document_fields(),
        }
    }
}

/// The manifest `Shape` descriptor and the two directions across it.
///
/// Decode is the direct tree walk (`document_value_decoding`) — the JSON
/// round-trip it replaces ground on the main thread in hang profiles.
/// Encode stays on the shaped path: the manifest `Shape` is what drives
/// `Int` vs `Double` on the way OUT, which a blind serializer cannot know.
mod coding {
    use serde::Serialize;
    use serde::de::DeserializeOwned;

    use replicaman::document_value::{DocumentFields, DocumentValue};
    use replicaman::document_value_decoding;

    #[allow(dead_code)]
    pub enum Shape {
        String,
        Integer,
        Number,
        Boolean,
        Json,
        Object(Vec<(&'static str, Shape)>),
        Array(Box<Shape>),
        Map(Box<Shape>),
    }

    impl Shape {
        pub fn object(fields: Vec<(&'static str, Shape)>) -> Self {
            Shape::Object(fields)
        }

        #[allow(dead_code)]
        pub fn array(item: Shape) -> Self {
            Shape::Array(Box::new(item))
        }
    }

    pub fn decode<Value: DeserializeOwned>(fields: &DocumentFields) -> Option<Value> {
        document_value_decoding::decode(fields).ok()
    }

    pub fn encode<Value: Serialize>(value: &Value, shape: &Shape) -> DocumentFields {
        let json = serde_json::to_value(value)
            .expect("generated document value did not match its manifest shape");

        match document_value(&json, shape) {
            DocumentValue::Map(fields) => fields,
            _ => panic!("generated document value did not match its manifest shape"),
        }
    }

    fn document_value(value: &serde_json::Value, shape: &Shape) -> DocumentValue {
        if value.is_null() {
            return DocumentValue::Null;
        }

        match shape {
            Shape::String => match value.as_str() {
                Some(value) => DocumentValue::String(value.to_owned()),
                None => DocumentValue::Null,
            },
            Shape::Integer => match value.as_i64().or_else(|| value.as_f64().map(|v| v as i64)) {
                Some(value) => DocumentValue::Int(value),
                None => DocumentValue::Null,
            },
            Shape::Number => match value.as_f64() {
                Some(value) => DocumentValue::Double(value),
                None => DocumentValue::Null,
            },
            Shape::Boolean => match value.as_bool() {
                Some(value) => DocumentValue::Bool(value),
                None => DocumentValue::Null,
            },
            Shape::Object(fields) => {
                let Some(object) = value.as_object() else {
                    return DocumentValue::Null;
                };
                DocumentValue::Map(
                    fields
                        .iter()
                        .map(|(key, shape)| {
                            let child = object
                                .get(*key)
                                .map(|value| document_value(value, shape))
                                .unwrap_or(DocumentValue::Null);
                            ((*key).to_owned(), child)
                        })
                        .collect(),
                )
            }
            Shape::Array(item) => match value.as_array() {
                Some(values) => {
                    DocumentValue::List(values.iter().map(|v| document_value(v, item)).collect())
                }
                None => DocumentValue::Null,
            },
            Shape::Map(item) => match value.as_object() {
                Some(object) => DocumentValue::Map(
                    object
                        .iter()
                        .map(|(key, v)| (key.clone(), document_value(v, item)))
                        .collect(),
                ),
                None => DocumentValue::Null,
            },
            Shape::Json => json_value(value),
        }
    }

    /// Under a `json` shape every numeric is a double — the manifest has said
    /// nothing about its kind, so there is nothing to preserve.
    fn json_value(value: &serde_json::Value) -> DocumentValue {
        match value {
            serde_json::Value::Null => DocumentValue::Null,
            serde_json::Value::Bool(value) => DocumentValue::Bool(*value),
            serde_json::Value::Number(value) => {
                DocumentValue::Double(value.as_f64().unwrap_or_default())
            }
            serde_json::Value::String(value) => DocumentValue::String(value.clone()),
            serde_json::Value::Array(values) => {
                DocumentValue::List(values.iter().map(json_value).collect())
            }
            serde_json::Value::Object(object) => DocumentValue::Map(
                object
                    .iter()
                    .map(|(key, value)| (key.clone(), json_value(value)))
                    .collect(),
            ),
        }
    }
}

use coding::Shape;
