// Generated by replica-codegen — DO NOT EDIT.
// Document value for stream `decks` · codec loro@1
//
// Rust cannot nest a type inside a struct, so the Swift emitter's nesting
// path is flattened into one identifier with the ROOT stripped
// (`DeckDocument.Slide.Style.ShadowOffset` → `SlideStyleShadowOffset`),
// except `meta`, which every document may carry (`DeckDocument.Meta` →
// `DeckDocumentMeta`).
// Enum cases keep the emitter's spelling with the first character
// upper-cased; a leading underscore (a raw value that starts with a digit)
// survives (`_169`, `_43`, `sdr` → `Sdr`). Struct fields are snake_case,
// which is already the document lane's wire spelling, so no serde rename is
// needed here. `new(..)` takes the fields with NO declared default, in
// declaration order; a struct whose fields all have defaults also gets
// `Default`. Decoding runs through a private all-`Option` `Raw` mirror: a
// declared default fills a missing key, an enum VALUE this build does not
// know collapses to the field's declared default, and a required field still
// refuses — while a LIST of enums stays strict, because the derived
// `Deserialize` is what decodes it.
//
// DeckDocument owns generated values; ReplicaMan owns the live document.

use serde::de::{self, Deserializer};
use serde::{Deserialize, Serialize};

use replicaman::document_value::DocumentEntry;
use replicaman::document_value::{DocumentFields, DocumentValue};

#[derive(Clone, Debug, Default, PartialEq)]
pub struct DeckProjection {
    pub layouts: Vec<DocumentEntry>,
    pub settings: DocumentFields,
    pub slides: Vec<DocumentEntry>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum SettingsAspectRatio {
    #[serde(rename = "4:3")]
    _43,
    #[serde(rename = "16:9")]
    _169,
}

impl SettingsAspectRatio {
    pub fn from_wire(wire: &str) -> Option<Self> {
        match wire {
            "4:3" => Some(SettingsAspectRatio::_43),
            "16:9" => Some(SettingsAspectRatio::_169),
            _ => None,
        }
    }

    pub fn as_wire(&self) -> &'static str {
        match self {
            SettingsAspectRatio::_43 => "4:3",
            SettingsAspectRatio::_169 => "16:9",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum SlideFitMode {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "contain")]
    Contain,
    #[serde(rename = "cover")]
    Cover,
}

impl SlideFitMode {
    pub fn from_wire(wire: &str) -> Option<Self> {
        match wire {
            "auto" => Some(SlideFitMode::Auto),
            "contain" => Some(SlideFitMode::Contain),
            "cover" => Some(SlideFitMode::Cover),
            _ => None,
        }
    }

    pub fn as_wire(&self) -> &'static str {
        match self {
            SlideFitMode::Auto => "auto",
            SlideFitMode::Contain => "contain",
            SlideFitMode::Cover => "cover",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum SlideStyleTextDecoration {
    #[serde(rename = "underline")]
    Underline,
    #[serde(rename = "strikethrough")]
    Strikethrough,
}

impl SlideStyleTextDecoration {
    pub fn from_wire(wire: &str) -> Option<Self> {
        match wire {
            "underline" => Some(SlideStyleTextDecoration::Underline),
            "strikethrough" => Some(SlideStyleTextDecoration::Strikethrough),
            _ => None,
        }
    }

    pub fn as_wire(&self) -> &'static str {
        match self {
            SlideStyleTextDecoration::Underline => "underline",
            SlideStyleTextDecoration::Strikethrough => "strikethrough",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct Layout {
    pub background_color: Option<String>,
    pub columns: i64,
    pub key: String,
    pub name: String,
    pub visible: bool,
}

impl Layout {
    pub fn new(key: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            background_color: None,
            columns: 1,
            key: key.into(),
            name: name.into(),
            visible: true,
        }
    }
}

impl<'de> Deserialize<'de> for Layout {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Raw {
            background_color: Option<String>,
            columns: Option<i64>,
            key: Option<String>,
            name: Option<String>,
            visible: Option<bool>,
        }

        let raw = Raw::deserialize(deserializer)?;

        Ok(Layout {
            background_color: raw.background_color,
            columns: raw.columns.unwrap_or(1),
            key: raw.key.ok_or_else(|| de::Error::missing_field("key"))?,
            name: raw.name.ok_or_else(|| de::Error::missing_field("name"))?,
            visible: raw.visible.unwrap_or(true),
        })
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct Settings {
    pub accent_color: Option<String>,
    pub aspect_ratio: SettingsAspectRatio,
    pub autoplay: bool,
    pub loop_count: i64,
}

impl Settings {
    pub fn new() -> Self {
        Self {
            accent_color: None,
            aspect_ratio: SettingsAspectRatio::_169,
            autoplay: false,
            loop_count: 0,
        }
    }
}

impl Default for Settings {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de> Deserialize<'de> for Settings {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Raw {
            accent_color: Option<String>,
            aspect_ratio: Option<String>,
            autoplay: Option<bool>,
            loop_count: Option<i64>,
        }

        let raw = Raw::deserialize(deserializer)?;

        Ok(Settings {
            accent_color: raw.accent_color,
            aspect_ratio: raw
                .aspect_ratio
                .as_deref()
                .and_then(SettingsAspectRatio::from_wire)
                .unwrap_or(SettingsAspectRatio::_169),
            autoplay: raw.autoplay.unwrap_or(false),
            loop_count: raw.loop_count.unwrap_or(0),
        })
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct SlideStyleShadowOffset {
    pub x: f64,
    pub y: f64,
}

impl SlideStyleShadowOffset {
    pub fn new() -> Self {
        Self { x: 0.0, y: 0.0 }
    }
}

impl Default for SlideStyleShadowOffset {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de> Deserialize<'de> for SlideStyleShadowOffset {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Raw {
            x: Option<f64>,
            y: Option<f64>,
        }

        let raw = Raw::deserialize(deserializer)?;

        Ok(SlideStyleShadowOffset {
            x: raw.x.unwrap_or(0.0),
            y: raw.y.unwrap_or(0.0),
        })
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct SlideStyle {
    pub fill_color: Option<String>,
    pub shadow_offset: Option<SlideStyleShadowOffset>,
    pub text_decoration: Option<Vec<SlideStyleTextDecoration>>,
}

impl SlideStyle {
    pub fn new() -> Self {
        Self {
            fill_color: None,
            shadow_offset: None,
            text_decoration: None,
        }
    }
}

impl Default for SlideStyle {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de> Deserialize<'de> for SlideStyle {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Raw {
            fill_color: Option<String>,
            shadow_offset: Option<SlideStyleShadowOffset>,
            text_decoration: Option<Vec<SlideStyleTextDecoration>>,
        }

        let raw = Raw::deserialize(deserializer)?;

        Ok(SlideStyle {
            fill_color: raw.fill_color,
            shadow_offset: raw.shadow_offset,
            text_decoration: raw.text_decoration,
        })
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct Slide {
    pub duration: f64,
    pub fit_mode: SlideFitMode,
    pub key: String,
    pub layout_key: String,
    pub opacity: f64,
    pub start: f64,
    pub style: Option<SlideStyle>,
}

impl Slide {
    pub fn new(
        duration: f64,
        key: impl Into<String>,
        layout_key: impl Into<String>,
        start: f64,
    ) -> Self {
        Self {
            duration,
            fit_mode: SlideFitMode::Auto,
            key: key.into(),
            layout_key: layout_key.into(),
            opacity: 1.0,
            start,
            style: None,
        }
    }
}

impl<'de> Deserialize<'de> for Slide {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Raw {
            duration: Option<f64>,
            fit_mode: Option<String>,
            key: Option<String>,
            layout_key: Option<String>,
            opacity: Option<f64>,
            start: Option<f64>,
            style: Option<SlideStyle>,
        }

        let raw = Raw::deserialize(deserializer)?;

        Ok(Slide {
            duration: raw
                .duration
                .ok_or_else(|| de::Error::missing_field("duration"))?,
            fit_mode: raw
                .fit_mode
                .as_deref()
                .and_then(SlideFitMode::from_wire)
                .unwrap_or(SlideFitMode::Auto),
            key: raw.key.ok_or_else(|| de::Error::missing_field("key"))?,
            layout_key: raw
                .layout_key
                .ok_or_else(|| de::Error::missing_field("layout_key"))?,
            opacity: raw.opacity.unwrap_or(1.0),
            start: raw.start.ok_or_else(|| de::Error::missing_field("start"))?,
            style: raw.style,
        })
    }
}

impl Layout {
    pub fn from_document_entry(entry: &DocumentEntry) -> Option<Self> {
        let mut fields = entry.fields.clone();
        fields.insert("key".to_owned(), DocumentValue::String(entry.key.clone()));

        coding::decode(&fields)
    }

    pub fn document_entry(&self) -> DocumentEntry {
        let mut fields = coding::encode(
            self,
            &Shape::object(vec![
                ("background_color", Shape::String),
                ("columns", Shape::Integer),
                ("key", Shape::String),
                ("name", Shape::String),
                ("visible", Shape::Boolean),
            ]),
        );
        fields.remove("key");

        DocumentEntry::new(self.key.clone(), fields)
    }
}

impl Slide {
    pub fn from_document_entry(entry: &DocumentEntry) -> Option<Self> {
        let mut fields = entry.fields.clone();
        fields.insert("key".to_owned(), DocumentValue::String(entry.key.clone()));

        coding::decode(&fields)
    }

    pub fn document_entry(&self) -> DocumentEntry {
        let mut fields = coding::encode(
            self,
            &Shape::object(vec![
                ("duration", Shape::Number),
                ("fit_mode", Shape::String),
                ("key", Shape::String),
                ("layout_key", Shape::String),
                ("opacity", Shape::Number),
                ("start", Shape::Number),
                (
                    "style",
                    Shape::object(vec![
                        ("fill_color", Shape::String),
                        (
                            "shadow_offset",
                            Shape::object(vec![("x", Shape::Number), ("y", Shape::Number)]),
                        ),
                        ("text_decoration", Shape::array(Shape::String)),
                    ]),
                ),
            ]),
        );
        fields.remove("key");

        DocumentEntry::new(self.key.clone(), fields)
    }
}

impl Settings {
    pub fn from_document_fields(fields: &DocumentFields) -> Option<Self> {
        coding::decode(fields)
    }

    pub fn document_fields(&self) -> DocumentFields {
        coding::encode(
            self,
            &Shape::object(vec![
                ("accent_color", Shape::String),
                ("aspect_ratio", Shape::String),
                ("autoplay", Shape::Boolean),
                ("loop_count", Shape::Integer),
            ]),
        )
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeckDocument {
    pub layouts: Vec<Layout>,
    pub settings: Settings,
    pub slides: Vec<Slide>,
}

impl DeckDocument {
    pub fn new(layouts: Vec<Layout>, settings: Settings, slides: Vec<Slide>) -> Self {
        Self {
            layouts,
            settings,
            slides,
        }
    }

    /// Refuse a partial typed document: round-tripping it would discard
    /// undecodable registry entries. The caller retains the raw projection.
    pub fn from_projection(projection: &DeckProjection) -> Option<Self> {
        let layouts_keys: std::collections::HashSet<_> =
            projection.layouts.iter().map(|entry| &entry.key).collect();
        if layouts_keys.len() != projection.layouts.len() {
            return None;
        }
        let settings = Settings::from_document_fields(&projection.settings)?;
        let slides_keys: std::collections::HashSet<_> =
            projection.slides.iter().map(|entry| &entry.key).collect();
        if slides_keys.len() != projection.slides.len() {
            return None;
        }

        Some(Self::new(
            projection
                .layouts
                .iter()
                .map(Layout::from_document_entry)
                .collect::<Option<Vec<_>>>()?,
            settings,
            projection
                .slides
                .iter()
                .map(Slide::from_document_entry)
                .collect::<Option<Vec<_>>>()?,
        ))
    }

    pub fn projection(&self) -> DeckProjection {
        DeckProjection {
            layouts: self.layouts.iter().map(Layout::document_entry).collect(),
            slides: self.slides.iter().map(Slide::document_entry).collect(),
            settings: self.settings.document_fields(),
        }
    }
}

/// The manifest `Shape` descriptor and the two directions across it.
///
/// Decode is the direct tree walk (`document_value_decoding`) — the JSON
/// round-trip it replaces ground on the main thread in hang profiles.
/// Encode stays on the shaped path: the manifest `Shape` is what drives
/// `Int` vs `Double` on the way OUT, which a blind serializer cannot know.
mod coding {
    use serde::Serialize;
    use serde::de::DeserializeOwned;

    use replicaman::document_value::{DocumentFields, DocumentValue};
    use replicaman::document_value_decoding;

    #[allow(dead_code)]
    pub enum Shape {
        String,
        Integer,
        Number,
        Boolean,
        Json,
        Object(Vec<(&'static str, Shape)>),
        Array(Box<Shape>),
        Map(Box<Shape>),
    }

    impl Shape {
        pub fn object(fields: Vec<(&'static str, Shape)>) -> Self {
            Shape::Object(fields)
        }

        #[allow(dead_code)]
        pub fn array(item: Shape) -> Self {
            Shape::Array(Box::new(item))
        }
    }

    pub fn decode<Value: DeserializeOwned>(fields: &DocumentFields) -> Option<Value> {
        document_value_decoding::decode(fields).ok()
    }

    pub fn encode<Value: Serialize>(value: &Value, shape: &Shape) -> DocumentFields {
        let json = serde_json::to_value(value)
            .expect("generated document value did not match its manifest shape");

        match document_value(&json, shape) {
            DocumentValue::Map(fields) => fields,
            _ => panic!("generated document value did not match its manifest shape"),
        }
    }

    fn document_value(value: &serde_json::Value, shape: &Shape) -> DocumentValue {
        if value.is_null() {
            return DocumentValue::Null;
        }

        match shape {
            Shape::String => match value.as_str() {
                Some(value) => DocumentValue::String(value.to_owned()),
                None => DocumentValue::Null,
            },
            Shape::Integer => match value.as_i64().or_else(|| value.as_f64().map(|v| v as i64)) {
                Some(value) => DocumentValue::Int(value),
                None => DocumentValue::Null,
            },
            Shape::Number => match value.as_f64() {
                Some(value) => DocumentValue::Double(value),
                None => DocumentValue::Null,
            },
            Shape::Boolean => match value.as_bool() {
                Some(value) => DocumentValue::Bool(value),
                None => DocumentValue::Null,
            },
            Shape::Object(fields) => {
                let Some(object) = value.as_object() else {
                    return DocumentValue::Null;
                };
                DocumentValue::Map(
                    fields
                        .iter()
                        .map(|(key, shape)| {
                            let child = object
                                .get(*key)
                                .map(|value| document_value(value, shape))
                                .unwrap_or(DocumentValue::Null);
                            ((*key).to_owned(), child)
                        })
                        .collect(),
                )
            }
            Shape::Array(item) => match value.as_array() {
                Some(values) => {
                    DocumentValue::List(values.iter().map(|v| document_value(v, item)).collect())
                }
                None => DocumentValue::Null,
            },
            Shape::Map(item) => match value.as_object() {
                Some(object) => DocumentValue::Map(
                    object
                        .iter()
                        .map(|(key, v)| (key.clone(), document_value(v, item)))
                        .collect(),
                ),
                None => DocumentValue::Null,
            },
            Shape::Json => json_value(value),
        }
    }

    /// Under a `json` shape every numeric is a double — the manifest has said
    /// nothing about its kind, so there is nothing to preserve.
    fn json_value(value: &serde_json::Value) -> DocumentValue {
        match value {
            serde_json::Value::Null => DocumentValue::Null,
            serde_json::Value::Bool(value) => DocumentValue::Bool(*value),
            serde_json::Value::Number(value) => {
                DocumentValue::Double(value.as_f64().unwrap_or_default())
            }
            serde_json::Value::String(value) => DocumentValue::String(value.clone()),
            serde_json::Value::Array(values) => {
                DocumentValue::List(values.iter().map(json_value).collect())
            }
            serde_json::Value::Object(object) => DocumentValue::Map(
                object
                    .iter()
                    .map(|(key, value)| (key.clone(), json_value(value)))
                    .collect(),
            ),
        }
    }
}

use coding::Shape;
