// Generated by replica-codegen — DO NOT EDIT.
// Defaults for document stream `decks`.
//
// Swift spells these as `static let` constants; a Rust value that owns a
// `String` is not const-constructible, so they are associated functions.
// Every field is written out, exactly as the Swift literal does — nothing
// is filled in by `Default`.

use super::deck_document::{Layout, Settings, SettingsAspectRatio};

pub struct DeckDefaults;

impl DeckDefaults {
    pub fn layouts() -> Vec<Layout> {
        vec![Layout {
            background_color: None,
            columns: 1,
            key: "title".to_owned(),
            name: "Title".to_owned(),
            visible: true,
        }]
    }

    pub fn settings() -> Settings {
        Settings {
            accent_color: None,
            aspect_ratio: SettingsAspectRatio::_169,
            autoplay: false,
            loop_count: 0,
        }
    }
}
