// Generated by replica-codegen — DO NOT EDIT.
// Document values · manifest version 1 · streams: boards, decks

mod board_defaults;
mod board_document;
mod deck_defaults;
mod deck_document;

pub use board_defaults::*;
pub use board_document::*;
pub use deck_defaults::*;
pub use deck_document::*;
