// Generated by replica-codegen — DO NOT EDIT.
// Defaults for document stream `boards`.

import Foundation

public enum BoardDefaults {
    public static let meta = BoardDocument.Meta(name: "Untitled")
}
