// Generated by replica-codegen — DO NOT EDIT.
// Document value for stream `boards` · codec loro@1
// BoardDocument owns generated values; BoardDoc edits the document through the Loro adapter.

import Foundation
import ReplicaMan

public struct BoardDocument: Sendable, Hashable, Codable {
    public var meta: Meta

    public init(meta: Meta) {
        self.meta = meta
    }

    private enum CodingKeys: String, CodingKey {
        case meta
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.meta = try container.decode(Meta.self, forKey: .meta)
    }

    public struct Meta: Sendable, Hashable, Codable {
        public var name: String

        public init(name: String = "Untitled") {
            self.name = name
        }

        private enum CodingKeys: String, CodingKey {
            case name
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.name = try container.decodeIfPresent(String.self, forKey: .name) ?? "Untitled"
        }
    }
}

private enum BoardDocumentCoding {
    indirect enum Shape {
        case string
        case integer
        case number
        case boolean
        case json
        case object([String: Shape])
        case array(Shape)
        case map(Shape)
    }

    // Direct tree decode (ReplicaValueCoding) — the JSON round-trip this
    // replaces ground on main in hang profiles (TextStyle(from:)
    // through JSONEncoder+JSONDecoder per typed read). Encode below stays
    // on the shaped JSON path: the manifest Shape drives .integer vs
    // .number on the way out.
    static func decode<Value: Decodable>(
        _ fields: [String: ReplicaValue],
        as type: Value.Type
    ) -> Value? {
        ReplicaDiagnostics.attemptOnce("decode a document \(Value.self)") {
            try ReplicaValueCoding.decode(type, from: .object(fields))
        }
    }

    static func encode<Value: Encodable>(
        _ value: Value,
        shape: Shape
    ) -> [String: ReplicaValue] {
        let encoder = JSONEncoder()
        encoder.keyEncodingStrategy = .convertToSnakeCase
        let object: Any
        do {
            object = try JSONSerialization.jsonObject(with: encoder.encode(value))
        } catch {
            preconditionFailure("generated document value did not encode: \(error)")
        }
        guard case let .object(fields) = documentValue(object, shape: shape) else {
            preconditionFailure("generated document value did not match its manifest shape")
        }
        return fields
    }

    private static func documentValue(_ value: Any, shape: Shape) -> ReplicaValue {
        if value is NSNull { return .null }

        switch shape {
        case .string:
            guard let value = value as? String else { return .null }
            return .string(value)
        case .integer:
            guard let value = value as? NSNumber else { return .null }
            return .integer(value.int64Value)
        case .number:
            guard let value = value as? NSNumber else { return .null }
            return .number(value.doubleValue)
        case .boolean:
            guard let value = value as? NSNumber else { return .null }
            return .bool(value.boolValue)
        case let .object(fields):
            guard let value = value as? [String: Any] else { return .null }
            return .object(Dictionary(uniqueKeysWithValues: fields.map { key, shape in
                let child = value[key].map { documentValue($0, shape: shape) } ?? .null
                return (key, child)
            }))
        case let .array(item):
            guard let value = value as? [Any] else { return .null }
            return .array(value.map { documentValue($0, shape: item) })
        case let .map(item):
            guard let value = value as? [String: Any] else { return .null }
            return .object(value.mapValues { documentValue($0, shape: item) })
        case .json:
            return jsonValue(value)
        }
    }

    private static func jsonValue(_ value: Any) -> ReplicaValue {
        switch value {
        case is NSNull:
            return .null
        case let value as String:
            return .string(value)
        case let value as [Any]:
            return .array(value.map(jsonValue))
        case let value as [String: Any]:
            return .object(value.mapValues(jsonValue))
        case let value as NSNumber:
            return String(cString: value.objCType) == "c"
                ? .bool(value.boolValue)
                : .number(value.doubleValue)
        default:
            return .null
        }
    }
}

extension BoardDocument.Meta {
    public init?(documentFields: [String: ReplicaValue]) {
        guard let decoded = BoardDocumentCoding.decode(documentFields, as: Self.self) else { return nil }
        self = decoded
    }

    public var documentFields: [String: ReplicaValue] {
        BoardDocumentCoding.encode(self, shape: .object(["name": .string]))
    }
}

extension BoardDocument {
    /// The roots the manifest declares as keyed registries — `key → entry`,
    /// each entry merging field by field.
    public static let registries: Set<String> = []

    public static func meta(in document: ReplicaValue) -> Meta? {
        guard document["meta"] == nil || document["meta"]?.object != nil else { return nil }
        return Meta(documentFields: document["meta"]?.object ?? [:])
    }

    /// The typed document off its materialized value (the adapter's
    /// `LoroDocument.value`).
    public init?(document: ReplicaValue) {
        guard document.object != nil else { return nil }
        guard let meta = Self.meta(in: document) else { return nil }
        self.init(
            meta: meta
        )
    }

    /// The document as the roots its birth seeds.
    public var documentRoots: [String: ReplicaValue] {
        [
            "meta": .object(meta.documentFields),
        ]
    }
}

