// Generated by replica-codegen — DO NOT EDIT.
// Defaults for document stream `decks`.

import Foundation

public enum DeckDefaults {
    public static let layouts: [DeckDocument.Layout] = [.init(backgroundColor: nil, columns: 1, key: "title", name: "Title", visible: true)]
    public static let settings = DeckDocument.Settings(accentColor: nil, aspectRatio: ._169, autoplay: false, loopCount: 0)
}
