// Generated by replica-codegen — DO NOT EDIT.
// Document value for stream `decks` · codec loro@1
// DeckDocument owns generated values; DeckDoc edits the document through the Loro adapter.

import Foundation
import ReplicaMan

public struct DeckDocument: Sendable, Hashable, Codable {
    public var layouts: [Layout]
    public var settings: Settings
    public var slides: [Slide]

    public init(layouts: [Layout], settings: Settings, slides: [Slide]) {
        self.layouts = layouts
        self.settings = settings
        self.slides = slides
    }

    private enum CodingKeys: String, CodingKey {
        case layouts, settings, slides
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.layouts = try container.decode([Layout].self, forKey: .layouts)
        self.settings = try container.decode(Settings.self, forKey: .settings)
        self.slides = try container.decode([Slide].self, forKey: .slides)
    }

    public struct Layout: Sendable, Hashable, Codable {
        public var backgroundColor: String? = nil
        public var columns: Int
        public var key: String
        public var name: String
        public var visible: Bool

        public init(backgroundColor: String? = nil, columns: Int = 1, key: String, name: String, visible: Bool = true) {
            self.backgroundColor = backgroundColor
            self.columns = columns
            self.key = key
            self.name = name
            self.visible = visible
        }

        private enum CodingKeys: String, CodingKey {
            case backgroundColor, columns, key, name, visible
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.backgroundColor = try container.decodeIfPresent(String.self, forKey: .backgroundColor)
            self.columns = try container.decodeIfPresent(Int.self, forKey: .columns) ?? 1
            self.key = try container.decode(String.self, forKey: .key)
            self.name = try container.decode(String.self, forKey: .name)
            self.visible = try container.decodeIfPresent(Bool.self, forKey: .visible) ?? true
        }
    }

    public struct Settings: Sendable, Hashable, Codable {
        public enum AspectRatio: String, Codable, Sendable, CaseIterable {
            case _43 = "4:3"
            case _169 = "16:9"
        }

        public var accentColor: String? = nil
        public var aspectRatio: AspectRatio
        public var autoplay: Bool
        public var loopCount: Int

        public init(accentColor: String? = nil, aspectRatio: AspectRatio = ._169, autoplay: Bool = false, loopCount: Int = 0) {
            self.accentColor = accentColor
            self.aspectRatio = aspectRatio
            self.autoplay = autoplay
            self.loopCount = loopCount
        }

        private enum CodingKeys: String, CodingKey {
            case accentColor, aspectRatio, autoplay, loopCount
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.accentColor = try container.decodeIfPresent(String.self, forKey: .accentColor)
            self.aspectRatio = (try container.decodeIfPresent(String.self, forKey: .aspectRatio)).flatMap(AspectRatio.init(rawValue:)) ?? ._169
            self.autoplay = try container.decodeIfPresent(Bool.self, forKey: .autoplay) ?? false
            self.loopCount = try container.decodeIfPresent(Int.self, forKey: .loopCount) ?? 0
        }
    }

    public struct Slide: Sendable, Hashable, Codable {
        public enum FitMode: String, Codable, Sendable, CaseIterable {
            case auto = "auto"
            case contain = "contain"
            case cover = "cover"
        }

        public var duration: Double
        public var fitMode: FitMode
        public var key: String
        public var layoutKey: String
        public var opacity: Double
        public var start: Double
        public var style: Style? = nil

        public init(duration: Double, fitMode: FitMode = .auto, key: String, layoutKey: String, opacity: Double = 1.0, start: Double, style: Style? = nil) {
            self.duration = duration
            self.fitMode = fitMode
            self.key = key
            self.layoutKey = layoutKey
            self.opacity = opacity
            self.start = start
            self.style = style
        }

        private enum CodingKeys: String, CodingKey {
            case duration, fitMode, key, layoutKey, opacity, start, style
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.duration = try container.decode(Double.self, forKey: .duration)
            self.fitMode = (try container.decodeIfPresent(String.self, forKey: .fitMode)).flatMap(FitMode.init(rawValue:)) ?? .auto
            self.key = try container.decode(String.self, forKey: .key)
            self.layoutKey = try container.decode(String.self, forKey: .layoutKey)
            self.opacity = try container.decodeIfPresent(Double.self, forKey: .opacity) ?? 1.0
            self.start = try container.decode(Double.self, forKey: .start)
            self.style = try container.decodeIfPresent(Style.self, forKey: .style)
        }

        public struct Style: Sendable, Hashable, Codable {
            public enum TextDecoration: String, Codable, Sendable, CaseIterable {
                case underline = "underline"
                case strikethrough = "strikethrough"
            }

            public var fillColor: String? = nil
            public var shadowOffset: ShadowOffset? = nil
            public var textDecoration: [TextDecoration]? = nil

            public init(fillColor: String? = nil, shadowOffset: ShadowOffset? = nil, textDecoration: [TextDecoration]? = nil) {
                self.fillColor = fillColor
                self.shadowOffset = shadowOffset
                self.textDecoration = textDecoration
            }

            private enum CodingKeys: String, CodingKey {
                case fillColor, shadowOffset, textDecoration
            }

            public init(from decoder: Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.fillColor = try container.decodeIfPresent(String.self, forKey: .fillColor)
                self.shadowOffset = try container.decodeIfPresent(ShadowOffset.self, forKey: .shadowOffset)
                self.textDecoration = try container.decodeIfPresent([TextDecoration].self, forKey: .textDecoration)
            }

            public struct ShadowOffset: Sendable, Hashable, Codable {
                public var x: Double
                public var y: Double

                public init(x: Double = 0.0, y: Double = 0.0) {
                    self.x = x
                    self.y = y
                }

                private enum CodingKeys: String, CodingKey {
                    case x, y
                }

                public init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: CodingKeys.self)
                    self.x = try container.decodeIfPresent(Double.self, forKey: .x) ?? 0.0
                    self.y = try container.decodeIfPresent(Double.self, forKey: .y) ?? 0.0
                }
            }
        }
    }
}

private enum DeckDocumentCoding {
    indirect enum Shape {
        case string
        case integer
        case number
        case boolean
        case json
        case object([String: Shape])
        case array(Shape)
        case map(Shape)
    }

    // Direct tree decode (ReplicaValueCoding) — the JSON round-trip this
    // replaces ground on main in hang profiles (TextStyle(from:)
    // through JSONEncoder+JSONDecoder per typed read). Encode below stays
    // on the shaped JSON path: the manifest Shape drives .integer vs
    // .number on the way out.
    static func decode<Value: Decodable>(
        _ fields: [String: ReplicaValue],
        as type: Value.Type
    ) -> Value? {
        ReplicaDiagnostics.attemptOnce("decode a document \(Value.self)") {
            try ReplicaValueCoding.decode(type, from: .object(fields))
        }
    }

    static func encode<Value: Encodable>(
        _ value: Value,
        shape: Shape
    ) -> [String: ReplicaValue] {
        let encoder = JSONEncoder()
        encoder.keyEncodingStrategy = .convertToSnakeCase
        let object: Any
        do {
            object = try JSONSerialization.jsonObject(with: encoder.encode(value))
        } catch {
            preconditionFailure("generated document value did not encode: \(error)")
        }
        guard case let .object(fields) = documentValue(object, shape: shape) else {
            preconditionFailure("generated document value did not match its manifest shape")
        }
        return fields
    }

    private static func documentValue(_ value: Any, shape: Shape) -> ReplicaValue {
        if value is NSNull { return .null }

        switch shape {
        case .string:
            guard let value = value as? String else { return .null }
            return .string(value)
        case .integer:
            guard let value = value as? NSNumber else { return .null }
            return .integer(value.int64Value)
        case .number:
            guard let value = value as? NSNumber else { return .null }
            return .number(value.doubleValue)
        case .boolean:
            guard let value = value as? NSNumber else { return .null }
            return .bool(value.boolValue)
        case let .object(fields):
            guard let value = value as? [String: Any] else { return .null }
            return .object(Dictionary(uniqueKeysWithValues: fields.map { key, shape in
                let child = value[key].map { documentValue($0, shape: shape) } ?? .null
                return (key, child)
            }))
        case let .array(item):
            guard let value = value as? [Any] else { return .null }
            return .array(value.map { documentValue($0, shape: item) })
        case let .map(item):
            guard let value = value as? [String: Any] else { return .null }
            return .object(value.mapValues { documentValue($0, shape: item) })
        case .json:
            return jsonValue(value)
        }
    }

    private static func jsonValue(_ value: Any) -> ReplicaValue {
        switch value {
        case is NSNull:
            return .null
        case let value as String:
            return .string(value)
        case let value as [Any]:
            return .array(value.map(jsonValue))
        case let value as [String: Any]:
            return .object(value.mapValues(jsonValue))
        case let value as NSNumber:
            return String(cString: value.objCType) == "c"
                ? .bool(value.boolValue)
                : .number(value.doubleValue)
        default:
            return .null
        }
    }
}

extension DeckDocument.Layout {
    /// An entry of the document's `layouts` registry: its key and its fields.
    public init?(key: String, documentFields: [String: ReplicaValue]) {
        var fields = documentFields
        fields["key"] = .string(key)
        guard let decoded = DeckDocumentCoding.decode(fields, as: Self.self) else { return nil }
        self = decoded
    }

    /// The entry's fields as the document holds them — the key is its
    /// slot's, never a field.
    public var documentFields: [String: ReplicaValue] {
        var fields = DeckDocumentCoding.encode(self, shape: .object(["background_color": .string, "columns": .integer, "key": .string, "name": .string, "visible": .boolean]))
        fields.removeValue(forKey: "key")
        return fields
    }
}

extension DeckDocument.Settings {
    public init?(documentFields: [String: ReplicaValue]) {
        guard let decoded = DeckDocumentCoding.decode(documentFields, as: Self.self) else { return nil }
        self = decoded
    }

    public var documentFields: [String: ReplicaValue] {
        DeckDocumentCoding.encode(self, shape: .object(["accent_color": .string, "aspect_ratio": .string, "autoplay": .boolean, "loop_count": .integer]))
    }
}

extension DeckDocument.Slide {
    /// An entry of the document's `slides` registry: its key and its fields.
    public init?(key: String, documentFields: [String: ReplicaValue]) {
        var fields = documentFields
        fields["key"] = .string(key)
        guard let decoded = DeckDocumentCoding.decode(fields, as: Self.self) else { return nil }
        self = decoded
    }

    /// The entry's fields as the document holds them — the key is its
    /// slot's, never a field.
    public var documentFields: [String: ReplicaValue] {
        var fields = DeckDocumentCoding.encode(self, shape: .object(["duration": .number, "fit_mode": .string, "key": .string, "layout_key": .string, "opacity": .number, "start": .number, "style": .object(["fill_color": .string, "shadow_offset": .object(["x": .number, "y": .number]), "text_decoration": .array(.string)])]))
        fields.removeValue(forKey: "key")
        return fields
    }
}

extension DeckDocument {
    /// The roots the manifest declares as keyed registries — `key → entry`,
    /// each entry merging field by field.
    public static let registries: Set<String> = ["layouts", "slides"]

    /// The `layouts` registry off a materialized document — a default
    /// entry's place first, then by key. This display read omits invalid
    /// entries. Use the complete document initializer before round-tripping.
    public static func layouts(in document: ReplicaValue) -> [Layout] {
        registry(document["layouts"], order: ["title"])
            .compactMap { Layout(key: $0.key, documentFields: $0.fields) }
    }

    public static func settings(in document: ReplicaValue) -> Settings? {
        guard document["settings"] == nil || document["settings"]?.object != nil else { return nil }
        return Settings(documentFields: document["settings"]?.object ?? [:])
    }

    /// The `slides` registry off a materialized document — a default
    /// entry's place first, then by key. This display read omits invalid
    /// entries. Use the complete document initializer before round-tripping.
    public static func slides(in document: ReplicaValue) -> [Slide] {
        registry(document["slides"], order: [])
            .compactMap { Slide(key: $0.key, documentFields: $0.fields) }
    }

    /// The typed document off its materialized value (the adapter's
    /// `LoroDocument.value`).
    public init?(document: ReplicaValue) {
        guard document.object != nil else { return nil }
        guard let layouts = Self.strictRegistry(document["layouts"], order: ["title"], decode: Layout.init(key:documentFields:)),
              let settings = Self.settings(in: document),
              let slides = Self.strictRegistry(document["slides"], order: [], decode: Slide.init(key:documentFields:)) else { return nil }
        self.init(
            layouts: layouts,
            settings: settings,
            slides: slides
        )
    }

    /// The document as the roots its birth seeds.
    public var documentRoots: [String: ReplicaValue] {
        [
            "layouts": .object(Dictionary(layouts.map { ($0.key, .object($0.documentFields)) }, uniquingKeysWith: { _, last in last })),
            "settings": .object(settings.documentFields),
            "slides": .object(Dictionary(slides.map { ($0.key, .object($0.documentFields)) }, uniquingKeysWith: { _, last in last })),
        ]
    }

    private static func strictRegistry<Value>(
        _ value: ReplicaValue?, order: [String], decode: (String, [String: ReplicaValue]) -> Value?
    ) -> [Value]? {
        guard let value else { return [] }
        guard let fields = value.object, fields.values.allSatisfy({ $0.object != nil }) else { return nil }
        var result: [Value] = []
        for entry in registry(value, order: order) {
            guard let decoded = decode(entry.key, entry.fields) else { return nil }
            result.append(decoded)
        }
        return result
    }

    private static func registry(_ value: ReplicaValue?, order: [String]) -> [(key: String, fields: [String: ReplicaValue])] {
        (value?.object ?? [:])
            .map { (key: $0.key, fields: $0.value.object ?? [:]) }
            .sorted { lhs, rhs in
                let left = order.firstIndex(of: lhs.key) ?? order.count
                let right = order.firstIndex(of: rhs.key) ?? order.count
                return left == right ? lhs.key < rhs.key : left < right
            }
    }
}

