// Generated by replica-codegen — DO NOT EDIT.
// Stream `decks` · document lane · codec loro@1 · shard user

import Foundation
import ReplicaMan


public struct Deck: ReplicaDocModel, ReplicaColumns, Equatable {
    public static let streamName = "decks"
    public enum Field: String, ReplicaIndexedField {
        case updatedAt = "updatedAt"
    }
    public enum Column: String, Sendable {
        case id = "id"
        case changeSeq = "changeSeq"
        case createdAt = "createdAt"
        case slideCount = "slideCount"
        case updatedAt = "updatedAt"
        case userId = "userId"
    }

    public var id: String
    public var changeSeq: Int
    public var createdAt: String
    public var slideCount: Int?
    public var updatedAt: String
    public var userId: Int

    public init(id: String, changeSeq: Int, createdAt: String, slideCount: Int? = nil, updatedAt: String, userId: Int) {
        self.id = id
        self.changeSeq = changeSeq
        self.createdAt = createdAt
        self.slideCount = slideCount
        self.updatedAt = updatedAt
        self.userId = userId
    }

    public init?(id: String, data fields: [String: ReplicaValue]) {
        guard let changeSeq = fields["changeSeq"]?.int else { return nil }
        guard let createdAt = fields["createdAt"]?.string else { return nil }
        guard let updatedAt = fields["updatedAt"]?.string else { return nil }
        guard let userId = fields["userId"]?.int else { return nil }
        self.id = id
        self.changeSeq = changeSeq
        self.createdAt = createdAt
        self.slideCount = fields["slideCount"]?.int
        self.updatedAt = updatedAt
        self.userId = userId
    }
}


extension DocumentStream where Model == Deck {
    @discardableResult
    public func create(id: String, changeSeq: Int, snapshot: Data, documentPeer: UInt64) async throws -> Bool {
        try await engine.createDoc(
            stream: Model.streamName,
            id: id,
            seed: snapshot,
            peer: documentPeer,
            data: [
                "changeSeq": .signedInteger(Int64(changeSeq)),
            ]
        )
    }
}

