// Generated by replica-codegen — DO NOT EDIT.
// Stream `exports` · row lane · shard user

import Foundation
import ReplicaMan

public enum ExportResult: Sendable, Hashable, Codable {
    case image(Image)
    case video(Video)
    case unknown(Shared)

    public struct Shared: Sendable, Hashable, Codable {
        public let kind: String

        public init(kind: String) {
            self.kind = kind
        }
    }

    public struct Image: Sendable, Hashable, Codable {
        public enum ColorSpace: String, Codable, Sendable, CaseIterable {
            case sdr = "sdr"
            case hdr = "hdr"
        }

        public let kind: String
        public var colorSpace: String? = nil
        public var height: Int
        public var histogram: [Int]? = nil
        public var width: Int

        public init(kind: String, colorSpace: String? = nil, height: Int, histogram: [Int]? = nil, width: Int) {
            self.kind = kind
            self.colorSpace = colorSpace
            self.height = height
            self.histogram = histogram
            self.width = width
        }

        private enum CodingKeys: String, CodingKey {
            case kind, colorSpace, height, histogram, width
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.kind = try container.decode(String.self, forKey: .kind)
            self.colorSpace = try container.decodeIfPresent(String.self, forKey: .colorSpace)
            self.height = try container.decode(Int.self, forKey: .height)
            self.histogram = try container.decodeIfPresent([Int].self, forKey: .histogram)
            self.width = try container.decode(Int.self, forKey: .width)
        }

        public var colorSpaceValue: ColorSpace? {
            get { colorSpace.flatMap { ColorSpace(rawValue: $0) } }
            set {
                if let newValue { colorSpace = newValue.rawValue }
                else { colorSpace = nil }
            }
        }
    }

    public struct Video: Sendable, Hashable, Codable {
        public enum ColorSpace: String, Codable, Sendable, CaseIterable {
            case sdr = "sdr"
            case hdr = "hdr"
        }

        public let kind: String
        public var colorSpace: String? = nil
        public var duration: Double
        public var frameRate: Double? = nil
        public var keyframes: [Double]? = nil
        public var mutedTracks: [Bool]? = nil

        public init(kind: String, colorSpace: String? = nil, duration: Double, frameRate: Double? = nil, keyframes: [Double]? = [], mutedTracks: [Bool]? = nil) {
            self.kind = kind
            self.colorSpace = colorSpace
            self.duration = duration
            self.frameRate = frameRate
            self.keyframes = keyframes
            self.mutedTracks = mutedTracks
        }

        private enum CodingKeys: String, CodingKey {
            case kind, colorSpace, duration, frameRate, keyframes, mutedTracks
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.kind = try container.decode(String.self, forKey: .kind)
            self.colorSpace = try container.decodeIfPresent(String.self, forKey: .colorSpace)
            self.duration = try container.decode(Double.self, forKey: .duration)
            self.frameRate = try container.decodeIfPresent(Double.self, forKey: .frameRate)
            self.keyframes = try container.decodeIfPresent([Double].self, forKey: .keyframes)
            self.mutedTracks = try container.decodeIfPresent([Bool].self, forKey: .mutedTracks)
        }

        public var colorSpaceValue: ColorSpace? {
            get { colorSpace.flatMap { ColorSpace(rawValue: $0) } }
            set {
                if let newValue { colorSpace = newValue.rawValue }
                else { colorSpace = nil }
            }
        }
    }

    private enum Probe: String, CodingKey {
        case discriminator = "kind"
    }

    public init(from decoder: Decoder) throws {
        let discriminator = try decoder.container(keyedBy: Probe.self)
            .decode(String.self, forKey: .discriminator)
        switch discriminator {
        case "image": self = .image(try Image(from: decoder))
        case "video": self = .video(try Video(from: decoder))
        default: self = .unknown(try Shared(from: decoder))
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .image(let value): try value.encode(to: encoder)
        case .video(let value): try value.encode(to: encoder)
        case .unknown(let value): try value.encode(to: encoder)
        }
    }

    public init?(replicaValue: ReplicaValue?) {
        guard let replicaValue,
              let decoded = try? ReplicaValueCoding.decode(Self.self, from: replicaValue)
        else { return nil }
        self = decoded
    }

    public var replicaValue: ReplicaValue {
        (try? ReplicaValueCoding.encode(self)) ?? .null
    }
}

extension ExportResult {
    public var asImage: Image? { if case .image(let value) = self { return value }; return nil }
    public var asVideo: Video? { if case .video(let value) = self { return value }; return nil }
}

public struct Export: ReplicaWritableRowModel, ReplicaColumns, Equatable {
    public static let streamName = "exports"
    public typealias Field = ReplicaNoField
    public enum Column: String, Sendable {
        case id = "id"
        case details = "details"
        case markers = "markers"
        case progress = "progress"
        case result = "result"
        case userId = "userId"
    }

    public var id: String
    public var details: ReplicaValue?
    public var markers: [Double]
    public var progress: Double
    public var resultJSON: ReplicaValue
    public var userId: String
    public var result: ExportResult? {
        didSet { resultJSON = result?.replicaValue ?? .object([:]) }
    }

    public init(id: String, details: ReplicaValue? = nil, markers: [Double], progress: Double, resultJSON: ReplicaValue, userId: String) {
        self.id = id
        self.details = details
        self.markers = markers
        self.progress = progress
        self.resultJSON = resultJSON
        self.userId = userId
        self.result = ExportResult(replicaValue: resultJSON)
    }

    public init?(id: String, type: String?, data fields: [String: ReplicaValue]) {
        guard let markers = (fields["markers"]?.items?.compactMap { $0.number }) else { return nil }
        guard let progress = fields["progress"]?.number else { return nil }
        guard let resultJSON = fields["result"] else { return nil }
        guard let userId = fields["userId"]?.string else { return nil }
        self.id = id
        self.details = fields["details"]
        self.markers = markers
        self.progress = progress
        self.resultJSON = resultJSON
        self.userId = userId
        self.result = ExportResult(replicaValue: resultJSON)
    }

    public var typeName: String? { nil }

    public func encode() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        encoded["details"] = details.map { value in value } ?? .null
        encoded["markers"] = .array(markers.map { .number($0) })
        encoded["progress"] = .number(progress)
        encoded["result"] = resultJSON
        encoded["userId"] = .string(userId)
        return encoded
    }

    public func encodeSnapshot() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        encoded["details"] = details.map { value in value } ?? .null
        encoded["markers"] = .array(markers.map { .number($0) })
        encoded["progress"] = .number(progress)
        encoded["result"] = resultJSON
        encoded["userId"] = .string(userId)
        return encoded
    }
}
