// Generated by replica-codegen — DO NOT EDIT.
// Stream `item_templates` · row lane · STI · shard user

import Foundation
import ReplicaMan

public enum ItemTemplateKind: String, Codable, Sendable, CaseIterable {
    case photoItem = "photoItem"
    case textItem = "textItem"
}

public enum ItemTemplateTone: String, Codable, Sendable, CaseIterable {
    case light = "light"
    case dark = "dark"
}

public struct PhotoItemTemplate: Identifiable, ReplicaVariant, ReplicaColumns, Sendable, Equatable {
    public static let streamName = "item_templates"
    public static let wireType = "PhotoItem"
    public enum Column: String, Sendable {
        case id = "id"
        case name = "name"
        case userId = "userId"
        case aspect = "aspect"
        case tone = "tone"
    }

    public var id: String
    public var name: String
    public var userId: String
    public var aspect: String?
    public var tone: ItemTemplateTone?

    public init(id: String, name: String, userId: String, aspect: String? = nil, tone: ItemTemplateTone? = nil) {
        self.id = id
        self.name = name
        self.userId = userId
        self.aspect = aspect
        self.tone = tone
    }
}

public struct TextItemTemplate: Identifiable, ReplicaVariant, ReplicaColumns, Sendable, Equatable {
    public static let streamName = "item_templates"
    public static let wireType = "TextItem"
    public enum Column: String, Sendable {
        case id = "id"
        case name = "name"
        case userId = "userId"
        case body = "body"
        case tone = "tone"
    }

    public var id: String
    public var name: String
    public var userId: String
    public var body: String?
    public var tone: ItemTemplateTone?

    public init(id: String, name: String, userId: String, body: String? = nil, tone: ItemTemplateTone? = nil) {
        self.id = id
        self.name = name
        self.userId = userId
        self.body = body
        self.tone = tone
    }
}

public enum ItemTemplate: ReplicaWritableRowModel, ReplicaColumns, Equatable {
    case photoItemTemplate(PhotoItemTemplate)
    case textItemTemplate(TextItemTemplate)

    public static let streamName = "item_templates"
    public typealias Field = ReplicaNoField
    public enum Column: String, Sendable {
        case id = "id"
        case name = "name"
        case userId = "userId"
    }

    public init?(id: String, type: String?, data fields: [String: ReplicaValue]) {
        guard let name = fields["name"]?.string else { return nil }
        guard let userId = fields["userId"]?.string else { return nil }
        switch type {
        case "PhotoItem":
            self = .photoItemTemplate(PhotoItemTemplate(
                id: id, name: name, userId: userId,
                aspect: fields["aspect"]?.string,
                tone: (fields["tone"]?.string.flatMap { ItemTemplateTone(rawValue: $0) })
            ))
        case "TextItem":
            self = .textItemTemplate(TextItemTemplate(
                id: id, name: name, userId: userId,
                body: fields["body"]?.string,
                tone: (fields["tone"]?.string.flatMap { ItemTemplateTone(rawValue: $0) })
            ))
        default:
            return nil
        }
    }

    public var id: String {
        switch self {
        case .photoItemTemplate(let model): return model.id
        case .textItemTemplate(let model): return model.id
        }
    }

    public var typeName: String? {
        switch self {
        case .photoItemTemplate: return "PhotoItem"
        case .textItemTemplate: return "TextItem"
        }
    }

    public func encode() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        switch self {
        case .photoItemTemplate(let model):
            encoded["name"] = .string(model.name)
            encoded["userId"] = .string(model.userId)
            encoded["aspect"] = model.aspect.map { value in .string(value) } ?? .null
            encoded["tone"] = model.tone.map { value in .string(value.rawValue) } ?? .null
        case .textItemTemplate(let model):
            encoded["name"] = .string(model.name)
            encoded["userId"] = .string(model.userId)
            encoded["body"] = model.body.map { value in .string(value) } ?? .null
            encoded["tone"] = model.tone.map { value in .string(value.rawValue) } ?? .null
        }
        return encoded
    }

    public func encodeSnapshot() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        switch self {
        case .photoItemTemplate(let model):
            encoded["name"] = .string(model.name)
            encoded["userId"] = .string(model.userId)
            encoded["aspect"] = model.aspect.map { value in .string(value) } ?? .null
            encoded["tone"] = model.tone.map { value in .string(value.rawValue) } ?? .null
        case .textItemTemplate(let model):
            encoded["name"] = .string(model.name)
            encoded["userId"] = .string(model.userId)
            encoded["body"] = model.body.map { value in .string(value) } ?? .null
            encoded["tone"] = model.tone.map { value in .string(value.rawValue) } ?? .null
        }
        return encoded
    }
}
