// Generated by replica-codegen — DO NOT EDIT.
// Stream `items` · row lane · STI · shard user

import Foundation
import ReplicaMan

public enum ItemKind: String, Codable, Sendable, CaseIterable {
    case photo = "photo"
    case text = "text"
}

public enum ItemLabel: String, Codable, Sendable, CaseIterable {
    case idea = "idea"
    case task = "task"
}

public enum ItemCaption: String, Codable, Sendable, CaseIterable {
    case wide = "wide"
    case square = "square"
}

public struct PhotoItem: Identifiable, ReplicaVariant, ReplicaColumns, Sendable, Equatable {
    public static let streamName = "items"
    public static let wireType = "PhotoItem"
    public enum Column: String, Sendable {
        case id = "id"
        case annotation = "annotation"
        case boardId = "boardId"
        case label = "label"
        case rank = "rank"
        case rankBadge = "rankBadge"
        case caption = "caption"
        case width = "width"
    }

    public var id: String
    public var annotation: String?
    public var boardId: String
    public var label: ItemLabel?
    public var rank: String
    public var rankBadge: String?
    public var caption: ItemCaption?
    public var width: Int?

    public init(id: String, annotation: String? = nil, boardId: String, label: ItemLabel? = nil, rank: String, rankBadge: String? = nil, caption: ItemCaption? = nil, width: Int? = nil) {
        self.id = id
        self.annotation = annotation
        self.boardId = boardId
        self.label = label
        self.rank = rank
        self.rankBadge = rankBadge
        self.caption = caption
        self.width = width
    }
}

public struct TextItem: Identifiable, ReplicaVariant, ReplicaColumns, Sendable, Equatable {
    public static let streamName = "items"
    public static let wireType = "TextItem"
    public enum Column: String, Sendable {
        case id = "id"
        case annotation = "annotation"
        case boardId = "boardId"
        case label = "label"
        case rank = "rank"
        case rankBadge = "rankBadge"
        case body = "body"
    }

    public var id: String
    public var annotation: String?
    public var boardId: String
    public var label: ItemLabel?
    public var rank: String
    public var rankBadge: String?
    public var body: String

    public init(id: String, annotation: String? = nil, boardId: String, label: ItemLabel? = nil, rank: String, rankBadge: String? = nil, body: String) {
        self.id = id
        self.annotation = annotation
        self.boardId = boardId
        self.label = label
        self.rank = rank
        self.rankBadge = rankBadge
        self.body = body
    }
}

public enum Item: ReplicaWritableRowModel, ReplicaColumns, Equatable {
    case photoItem(PhotoItem)
    case textItem(TextItem)

    public static let streamName = "items"
    public enum Field: String, ReplicaIndexedField {
        case boardId = "boardId"
    }
    public enum Column: String, Sendable {
        case id = "id"
        case annotation = "annotation"
        case boardId = "boardId"
        case label = "label"
        case rank = "rank"
        case rankBadge = "rankBadge"
    }

    public init?(id: String, type: String?, data fields: [String: ReplicaValue]) {
        guard let boardId = fields["boardId"]?.string else { return nil }
        guard let rank = fields["rank"]?.string else { return nil }
        switch type {
        case "PhotoItem":
            self = .photoItem(PhotoItem(
                id: id, annotation: fields["annotation"]?.string, boardId: boardId, label: (fields["label"]?.string.flatMap { ItemLabel(rawValue: $0) }), rank: rank, rankBadge: fields["rankBadge"]?.string,
                caption: (fields["caption"]?.string.flatMap { ItemCaption(rawValue: $0) }),
                width: fields["width"]?.int
            ))
        case "TextItem":
            guard let body = fields["body"]?.string else { return nil }
            self = .textItem(TextItem(
                id: id, annotation: fields["annotation"]?.string, boardId: boardId, label: (fields["label"]?.string.flatMap { ItemLabel(rawValue: $0) }), rank: rank, rankBadge: fields["rankBadge"]?.string,
                body: body
            ))
        default:
            return nil
        }
    }

    public var id: String {
        switch self {
        case .photoItem(let model): return model.id
        case .textItem(let model): return model.id
        }
    }

    public var typeName: String? {
        switch self {
        case .photoItem: return "PhotoItem"
        case .textItem: return "TextItem"
        }
    }

    public func encode() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        switch self {
        case .photoItem(let model):
            encoded["annotation"] = model.annotation.map { value in .string(value) } ?? .null
            encoded["boardId"] = .string(model.boardId)
            encoded["label"] = model.label.map { value in .string(value.rawValue) } ?? .null
            encoded["rank"] = .string(model.rank)
            encoded["caption"] = model.caption.map { value in .string(value.rawValue) } ?? .null
            encoded["width"] = model.width.map { value in .signedInteger(Int64(value)) } ?? .null
        case .textItem(let model):
            encoded["annotation"] = model.annotation.map { value in .string(value) } ?? .null
            encoded["boardId"] = .string(model.boardId)
            encoded["label"] = model.label.map { value in .string(value.rawValue) } ?? .null
            encoded["rank"] = .string(model.rank)
            encoded["body"] = .string(model.body)
        }
        return encoded
    }

    public func encodeSnapshot() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        switch self {
        case .photoItem(let model):
            encoded["annotation"] = model.annotation.map { value in .string(value) } ?? .null
            encoded["boardId"] = .string(model.boardId)
            encoded["label"] = model.label.map { value in .string(value.rawValue) } ?? .null
            encoded["rank"] = .string(model.rank)
            encoded["rankBadge"] = model.rankBadge.map { value in .string(value) } ?? .null
            encoded["caption"] = model.caption.map { value in .string(value.rawValue) } ?? .null
            encoded["width"] = model.width.map { value in .signedInteger(Int64(value)) } ?? .null
        case .textItem(let model):
            encoded["annotation"] = model.annotation.map { value in .string(value) } ?? .null
            encoded["boardId"] = .string(model.boardId)
            encoded["label"] = model.label.map { value in .string(value.rawValue) } ?? .null
            encoded["rank"] = .string(model.rank)
            encoded["rankBadge"] = model.rankBadge.map { value in .string(value) } ?? .null
            encoded["body"] = .string(model.body)
        }
        return encoded
    }
}
