// Generated by replica-codegen — DO NOT EDIT.
// Manifest version 1 · streams: boards, decks, exports, item_templates, items, jobs, tallies, themes, tickets, workflows

import Foundation
import ReplicaMan

public struct SampleReplica: Sendable {
    public static let schema = ReplicaSchema(streams: [
        ReplicaStreamSpec(name: "boards", lane: .document, readonly: false, shard: "user", codec: "loro@1", reflections: [ReplicaReflection(field: "name", path: ["meta", "name"])]),
        ReplicaStreamSpec(name: "decks", lane: .document, readonly: false, shard: "user", codec: "loro@1", stamp: .standard),
        ReplicaStreamSpec(name: "exports", lane: .row, readonly: false, shard: "user", pushed: ["details", "markers", "progress", "result", "userId"]),
        ReplicaStreamSpec(name: "item_templates", lane: .row, readonly: false, shard: "user", pushed: ["aspect", "body", "name", "tone", "userId"]),
        ReplicaStreamSpec(name: "items", lane: .row, readonly: false, shard: "user", pushed: ["annotation", "boardId", "body", "caption", "label", "rank", "width"]),
        ReplicaStreamSpec(name: "jobs", lane: .row, readonly: true, shard: "user"),
        ReplicaStreamSpec(name: "tallies", lane: .row, readonly: false, shard: "user", preconditions: ["status", "version"], pushed: ["count", "status", "userId", "version"]),
        ReplicaStreamSpec(name: "themes", lane: .row, readonly: false, shard: "user", pushed: ["colors", "description", "heading", "logoRef", "name", "pinned"]),
        ReplicaStreamSpec(name: "tickets", lane: .row, readonly: true, shard: "user"),
        ReplicaStreamSpec(name: "workflows", lane: .row, readonly: true, shard: "global"),
    ], indexes: [
        ReplicaIndexSpec(stream: "decks", field: "updatedAt", kind: .btree),
        ReplicaIndexSpec(stream: "items", field: "boardId", kind: .btree),
        ReplicaIndexSpec(stream: "tickets", field: "note", kind: .fts5),
        ReplicaIndexSpec(stream: "tickets", field: "userId", kind: .btree),
    ], namespace: "replicaman-test", version: 1)

    public let engine: ReplicaEngine

    public init(engine: ReplicaEngine) {
        self.engine = engine
    }

    public var boards: DocumentStream<Board> { DocumentStream(engine: engine) }
    public var decks: DocumentStream<Deck> { DocumentStream(engine: engine) }
    public var exports: RowStream<Export> { RowStream(engine: engine) }
    public var itemTemplates: RowStream<ItemTemplate> { RowStream(engine: engine) }
    public var items: RowStream<Item> { RowStream(engine: engine) }
    public var jobs: RowStream<Job> { RowStream(engine: engine) }
    public var tallies: RowStream<Tally> { RowStream(engine: engine) }
    public var themes: RowStream<Theme> { RowStream(engine: engine) }
    public var tickets: RowStream<Ticket> { RowStream(engine: engine) }
    public var workflows: RowStream<Workflow> { RowStream(engine: engine) }

    /// One local transaction: read, decide and write under the writer.
    @discardableResult
    public func write<T>(_ body: (ReplicaTransaction) throws -> T) throws -> T {
        try engine.write(body)
    }

    @discardableResult
    public func write<T: Sendable>(_ body: @escaping @Sendable (ReplicaTransaction) throws -> T) async throws -> T {
        try await engine.write(body)
    }
}

extension ReplicaTransaction {
    public var exports: TransactionRows<Export> { rows(Export.self) }
    public var itemTemplates: TransactionRows<ItemTemplate> { rows(ItemTemplate.self) }
    public var items: TransactionRows<Item> { rows(Item.self) }
    public var jobs: TransactionReadonlyRows<Job> { readonlyRows(Job.self) }
    public var tallies: TransactionRows<Tally> { rows(Tally.self) }
    public var themes: TransactionRows<Theme> { rows(Theme.self) }
    public var tickets: TransactionReadonlyRows<Ticket> { readonlyRows(Ticket.self) }
    public var workflows: TransactionReadonlyRows<Workflow> { readonlyRows(Workflow.self) }
}
