// Generated by replica-codegen — DO NOT EDIT.
// Stream `tallies` · row lane · shard user

import Foundation
import ReplicaMan


public struct Tally: ReplicaWritableRowModel, ReplicaColumns, Equatable {
    public static let streamName = "tallies"
    public typealias Field = ReplicaNoField
    public enum Column: String, Sendable {
        case id = "id"
        case count = "count"
        case status = "status"
        case userId = "userId"
        case version = "version"
    }

    public var id: String
    public var count: Int
    public var status: String
    public var userId: String
    public var version: Int

    public init(id: String, count: Int, status: String, userId: String, version: Int) {
        self.id = id
        self.count = count
        self.status = status
        self.userId = userId
        self.version = version
    }

    public init?(id: String, type: String?, data fields: [String: ReplicaValue]) {
        guard let count = fields["count"]?.int else { return nil }
        guard let status = fields["status"]?.string else { return nil }
        guard let userId = fields["userId"]?.string else { return nil }
        guard let version = fields["version"]?.int else { return nil }
        self.id = id
        self.count = count
        self.status = status
        self.userId = userId
        self.version = version
    }

    public var typeName: String? { nil }

    public func encode() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        encoded["count"] = .signedInteger(Int64(count))
        encoded["status"] = .string(status)
        encoded["userId"] = .string(userId)
        encoded["version"] = .signedInteger(Int64(version))
        return encoded
    }

    public func encodeSnapshot() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        encoded["count"] = .signedInteger(Int64(count))
        encoded["status"] = .string(status)
        encoded["userId"] = .string(userId)
        encoded["version"] = .signedInteger(Int64(version))
        return encoded
    }
}
