// Generated by replica-codegen — DO NOT EDIT.
// Stream `themes` · row lane · shard user

import Foundation
import ReplicaMan

public struct ThemeColor: Sendable, Hashable, Codable {
    public var hex: String
    public var id: String

    public init(hex: String, id: String) {
        self.hex = hex
        self.id = id
    }

    private enum CodingKeys: String, CodingKey {
        case hex, id
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.hex = try container.decode(String.self, forKey: .hex)
        self.id = try container.decode(String.self, forKey: .id)
    }
}
public struct ThemeHeading: Sendable, Hashable, Codable {
    public var font: Font? = nil
    public var uppercase: Bool

    public init(font: Font? = nil, uppercase: Bool = false) {
        self.font = font
        self.uppercase = uppercase
    }

    private enum CodingKeys: String, CodingKey {
        case font, uppercase
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.font = try container.decodeIfPresent(Font.self, forKey: .font)
        self.uppercase = try container.decodeIfPresent(Bool.self, forKey: .uppercase) ?? false
    }

    public struct Font: Sendable, Hashable, Codable {
        public enum Slant: String, Codable, Sendable, CaseIterable {
            case upright = "upright"
            case italic = "italic"
        }

        public var family: String
        public var slant: Slant? = nil
        public var weight: Int? = nil

        public init(family: String, slant: Slant? = .upright, weight: Int? = 400) {
            self.family = family
            self.slant = slant
            self.weight = weight
        }

        private enum CodingKeys: String, CodingKey {
            case family, slant, weight
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.family = try container.decode(String.self, forKey: .family)
            self.slant = (try container.decodeIfPresent(String.self, forKey: .slant)).flatMap(Slant.init(rawValue:))
            self.weight = try container.decodeIfPresent(Int.self, forKey: .weight)
        }
    }
}
public struct Theme: ReplicaWritableRowModel, ReplicaColumns, Equatable {
    public static let streamName = "themes"
    public typealias Field = ReplicaNoField
    public enum Column: String, Sendable {
        case id = "id"
        case colors = "colors"
        case createdAt = "createdAt"
        case description = "description"
        case heading = "heading"
        case logoRef = "logoRef"
        case logoUrl = "logoUrl"
        case name = "name"
        case pinned = "pinned"
        case updatedAt = "updatedAt"
        case userId = "userId"
    }

    public var id: String
    public var colors: [ThemeColor]
    public var createdAt: String
    public var description: String?
    public var heading: ThemeHeading?
    public var logoRef: String?
    public var logoUrl: String?
    public var name: String
    public var pinned: Bool?
    public var updatedAt: String
    public var userId: Int

    public init(id: String, colors: [ThemeColor], createdAt: String, description: String? = nil, heading: ThemeHeading? = nil, logoRef: String? = nil, logoUrl: String? = nil, name: String, pinned: Bool? = nil, updatedAt: String, userId: Int) {
        self.id = id
        self.colors = colors
        self.createdAt = createdAt
        self.description = description
        self.heading = heading
        self.logoRef = logoRef
        self.logoUrl = logoUrl
        self.name = name
        self.pinned = pinned
        self.updatedAt = updatedAt
        self.userId = userId
    }

    public init?(id: String, type: String?, data fields: [String: ReplicaValue]) {
        guard let colors = (fields["colors"].flatMap { try? ReplicaValueCoding.decode([ThemeColor].self, from: $0) }) else { return nil }
        guard let createdAt = fields["createdAt"]?.string else { return nil }
        guard let name = fields["name"]?.string else { return nil }
        guard let updatedAt = fields["updatedAt"]?.string else { return nil }
        guard let userId = fields["userId"]?.int else { return nil }
        self.id = id
        self.colors = colors
        self.createdAt = createdAt
        self.description = fields["description"]?.string
        self.heading = (fields["heading"].flatMap { try? ReplicaValueCoding.decode(ThemeHeading.self, from: $0) })
        self.logoRef = fields["logoRef"]?.string
        self.logoUrl = fields["logoUrl"]?.string
        self.name = name
        self.pinned = fields["pinned"]?.bool
        self.updatedAt = updatedAt
        self.userId = userId
    }

    public var typeName: String? { nil }

    public func encode() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        encoded["colors"] = ((try? ReplicaValueCoding.encode(colors)) ?? .null)
        encoded["description"] = description.map { value in .string(value) } ?? .null
        encoded["heading"] = heading.map { value in ((try? ReplicaValueCoding.encode(value)) ?? .null) } ?? .null
        encoded["logoRef"] = logoRef.map { value in .string(value) } ?? .null
        encoded["name"] = .string(name)
        encoded["pinned"] = pinned.map { value in .bool(value) } ?? .null
        return encoded
    }

    public func encodeSnapshot() -> [String: ReplicaValue] {
        var encoded: [String: ReplicaValue] = [:]
        encoded["colors"] = ((try? ReplicaValueCoding.encode(colors)) ?? .null)
        encoded["createdAt"] = .string(createdAt)
        encoded["description"] = description.map { value in .string(value) } ?? .null
        encoded["heading"] = heading.map { value in ((try? ReplicaValueCoding.encode(value)) ?? .null) } ?? .null
        encoded["logoRef"] = logoRef.map { value in .string(value) } ?? .null
        encoded["logoUrl"] = logoUrl.map { value in .string(value) } ?? .null
        encoded["name"] = .string(name)
        encoded["pinned"] = pinned.map { value in .bool(value) } ?? .null
        encoded["updatedAt"] = .string(updatedAt)
        encoded["userId"] = .signedInteger(Int64(userId))
        return encoded
    }
}
