// Generated by replica-codegen — DO NOT EDIT.
// Stream `tickets` · row lane · readonly · shard user

import Foundation
import ReplicaMan


public struct Ticket: ReplicaRowModel, ReplicaColumns, Equatable {
    public static let streamName = "tickets"
    public enum Field: String, ReplicaIndexedField {
        case note = "note"
        case userId = "userId"
    }
    public enum Column: String, Sendable {
        case id = "id"
        case note = "note"
        case userId = "userId"
    }

    public var id: String
    public var note: String?
    public var userId: String

    public init(id: String, note: String? = nil, userId: String) {
        self.id = id
        self.note = note
        self.userId = userId
    }

    public init?(id: String, type: String?, data fields: [String: ReplicaValue]) {
        guard let userId = fields["userId"]?.string else { return nil }
        self.id = id
        self.note = fields["note"]?.string
        self.userId = userId
    }

    public var typeName: String? { nil }

    public func encode() -> [String: ReplicaValue] {
        [:]
    }
}
