// Generated by replica-codegen — DO NOT EDIT.
// Stream `workflows` · row lane · readonly · shard global

import Foundation
import ReplicaMan

public struct WorkflowGraph: Sendable, Hashable, Codable {
    public var links: [String: Links]
    public var publishedAt: String? = nil
    public var steps: [String: Steps]

    public init(links: [String: Links] = [:], publishedAt: String? = nil, steps: [String: Steps] = [:]) {
        self.links = links
        self.publishedAt = publishedAt
        self.steps = steps
    }

    private enum CodingKeys: String, CodingKey {
        case links, publishedAt, steps
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.links = try container.decodeIfPresent([String: Links].self, forKey: .links) ?? [:]
        self.publishedAt = try container.decodeIfPresent(String.self, forKey: .publishedAt)
        self.steps = try container.decodeIfPresent([String: Steps].self, forKey: .steps) ?? [:]
    }

    public struct Links: Sendable, Hashable, Codable {
        public var from: String
        public var index: Int
        public var to: String

        public init(from: String, index: Int = 0, to: String) {
            self.from = from
            self.index = index
            self.to = to
        }

        private enum CodingKeys: String, CodingKey {
            case from, index, to
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.from = try container.decode(String.self, forKey: .from)
            self.index = try container.decodeIfPresent(Int.self, forKey: .index) ?? 0
            self.to = try container.decode(String.self, forKey: .to)
        }
    }

    public struct Steps: Sendable, Hashable, Codable {
        public var kind: String
        public var options: ReplicaValue

        public init(kind: String, options: ReplicaValue = .object([:])) {
            self.kind = kind
            self.options = options
        }

        private enum CodingKeys: String, CodingKey {
            case kind, options
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.kind = try container.decode(String.self, forKey: .kind)
            self.options = try container.decodeIfPresent(ReplicaValue.self, forKey: .options) ?? .object([:])
        }
    }
}
public struct Workflow: ReplicaRowModel, ReplicaColumns, Equatable {
    public static let streamName = "workflows"
    public typealias Field = ReplicaNoField
    public enum Column: String, Sendable {
        case id = "id"
        case graph = "graph"
        case version = "version"
    }

    public var id: String
    public var graph: WorkflowGraph
    public var version: Int

    public init(id: String, graph: WorkflowGraph, version: Int) {
        self.id = id
        self.graph = graph
        self.version = version
    }

    public init?(id: String, type: String?, data fields: [String: ReplicaValue]) {
        guard let graph = (fields["graph"].flatMap { try? ReplicaValueCoding.decode(WorkflowGraph.self, from: $0) }) else { return nil }
        guard let version = fields["version"]?.int else { return nil }
        self.id = id
        self.graph = graph
        self.version = version
    }

    public var typeName: String? { nil }

    public func encode() -> [String: ReplicaValue] {
        [:]
    }
}
