// Generated by replica-codegen — DO NOT EDIT.
// Defaults for document stream `boards`.

package io.replicaman.generated.app.documents

public object BoardDefaults {
    public val meta: BoardDocument.Meta = BoardDocument.Meta(name = "Untitled")
}
