// Generated by replica-codegen — DO NOT EDIT.
// Defaults for document stream `decks`.

package io.replicaman.generated.app.documents

public object DeckDefaults {
    public val layouts: List<DeckDocument.Layout> = listOf(DeckDocument.Layout(backgroundColor = null, columns = 1L, key = "title", name = "Title", visible = true))
    public val settings: DeckDocument.Settings = DeckDocument.Settings(accentColor = null, aspectRatio = DeckDocument.Settings.AspectRatio._169, autoplay = false, loopCount = 0L)
}
