// Generated by replica-codegen — DO NOT EDIT.
// Document value for stream `decks` · codec loro@1
// DeckDocument owns generated values; DeckDoc owns the Loro-backed editing engine.

package io.replicaman.generated.app.documents

import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.SerializationStrategy
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNamingStrategy
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.longOrNull
import kotlinx.serialization.serializer
import io.replicaman.DocumentEntry
import io.replicaman.DocumentValue
import io.replicaman.DocumentValueDecoding

@Serializable
public data class DeckDocument(
    public val layouts: List<Layout>,
    public val settings: Settings,
    public val slides: List<Slide>,
) {
    @Serializable
    public data class Layout(
        public val backgroundColor: String? = null,
        public val columns: Long = 1L,
        public val key: String,
        public val name: String,
        public val visible: Boolean = true,
    ) {
        public companion object
    }

    @Serializable
    public data class Settings(
        public val accentColor: String? = null,
        public val aspectRatio: AspectRatio = AspectRatio._169,
        public val autoplay: Boolean = false,
        public val loopCount: Long = 0L,
    ) {
        @Serializable
        public enum class AspectRatio(public val rawValue: String) {
            @SerialName("4:3") _43("4:3"),
            @SerialName("16:9") _169("16:9"),
            ;

            public companion object {
                public fun fromRaw(rawValue: String): AspectRatio? = entries.find { it.rawValue == rawValue }
            }
        }

        public companion object
    }

    @Serializable
    public data class Slide(
        public val duration: Double,
        public val fitMode: FitMode = FitMode.AUTO,
        public val key: String,
        public val layoutKey: String,
        public val opacity: Double = 1.0,
        public val start: Double,
        public val style: Style? = null,
    ) {
        @Serializable
        public enum class FitMode(public val rawValue: String) {
            @SerialName("auto") AUTO("auto"),
            @SerialName("contain") CONTAIN("contain"),
            @SerialName("cover") COVER("cover"),
            ;

            public companion object {
                public fun fromRaw(rawValue: String): FitMode? = entries.find { it.rawValue == rawValue }
            }
        }

        @Serializable
        public data class Style(
            public val fillColor: String? = null,
            public val shadowOffset: ShadowOffset? = null,
            public val textDecoration: List<TextDecoration>? = null,
        ) {
            @Serializable
            public enum class TextDecoration(public val rawValue: String) {
                @SerialName("underline") UNDERLINE("underline"),
                @SerialName("strikethrough") STRIKETHROUGH("strikethrough"),
                ;

                public companion object {
                    public fun fromRaw(rawValue: String): TextDecoration? = entries.find { it.rawValue == rawValue }
                }
            }

            @Serializable
            public data class ShadowOffset(
                public val x: Double = 0.0,
                public val y: Double = 0.0,
            )
        }

        public companion object
    }

    public companion object
}

private object DeckDocumentCoding {
    public sealed interface Shape {
        public data object String : Shape
        public data object Integer : Shape
        public data object Number : Shape
        public data object Boolean : Shape
        public data object Json : Shape
        public data class Object(val fields: kotlin.collections.Map<kotlin.String, Shape>) : Shape
        public data class Array(val item: Shape) : Shape
        public data class Map(val item: Shape) : Shape
    }

    // Direct tree decode (io.replicaman.DocumentValueDecoding) — the JSON
    // round-trip this replaces ground on main in hang profiles
    // (TextStyle decode through Json encode+decode per typed read).
    // Encode below stays on the shaped JSON path: the manifest Shape
    // drives .Int vs .Double on the way out.
    @OptIn(ExperimentalSerializationApi::class)
    fun <Value> decode(
        fields: kotlin.collections.Map<kotlin.String, DocumentValue>,
        deserializer: DeserializationStrategy<Value>,
    ): Value? = try {
        DocumentValueDecoding.decode(deserializer, fields)
    } catch (error: Exception) {
        io.replicaman.ReplicaDiagnostics.report("decode a document ${deserializer.descriptor.serialName}", error)
        null
    }

    @OptIn(ExperimentalSerializationApi::class)
    private val json = Json {
        namingStrategy = JsonNamingStrategy.SnakeCase
        encodeDefaults = true
        explicitNulls = true
    }

    fun <Value> encode(
        value: Value,
        serializer: SerializationStrategy<Value>,
        shape: Shape,
    ): kotlin.collections.Map<kotlin.String, DocumentValue> {
        val encoded = documentValue(json.encodeToJsonElement(serializer, value), shape)
        val fields = (encoded as? DocumentValue.Map)?.value
        checkNotNull(fields) { "generated deck document value did not match its manifest shape" }
        return fields
    }

    private fun documentValue(value: JsonElement, shape: Shape): DocumentValue {
        if (value is JsonNull) return DocumentValue.Null

        return when (shape) {
            Shape.String -> (value as? JsonPrimitive)?.takeIf { it.isString }
                ?.let { DocumentValue.String(it.content) } ?: DocumentValue.Null
            Shape.Integer -> (value as? JsonPrimitive)
                ?.let { it.longOrNull ?: it.doubleOrNull?.toLong() }
                ?.let { DocumentValue.Int(it) } ?: DocumentValue.Null
            Shape.Number -> (value as? JsonPrimitive)?.doubleOrNull
                ?.let { DocumentValue.Double(it) } ?: DocumentValue.Null
            Shape.Boolean -> (value as? JsonPrimitive)?.booleanOrNull
                ?.let { DocumentValue.Bool(it) } ?: DocumentValue.Null
            is Shape.Object -> {
                val bag = value as? JsonObject ?: return DocumentValue.Null
                DocumentValue.Map(
                    shape.fields.mapValues { (key, child) ->
                        bag[key]?.let { documentValue(it, child) } ?: DocumentValue.Null
                    },
                )
            }
            is Shape.Array -> {
                val items = value as? JsonArray ?: return DocumentValue.Null
                DocumentValue.List(items.map { documentValue(it, shape.item) })
            }
            is Shape.Map -> {
                val bag = value as? JsonObject ?: return DocumentValue.Null
                DocumentValue.Map(bag.mapValues { documentValue(it.value, shape.item) })
            }
            Shape.Json -> jsonValue(value)
        }
    }

    private fun jsonValue(value: JsonElement): DocumentValue = when (value) {
        is JsonNull -> DocumentValue.Null
        is JsonArray -> DocumentValue.List(value.map(::jsonValue))
        is JsonObject -> DocumentValue.Map(value.mapValues { jsonValue(it.value) })
        is JsonPrimitive ->
            if (value.isString) {
                DocumentValue.String(value.content)
            } else {
                value.booleanOrNull?.let(DocumentValue::Bool)
                    ?: value.doubleOrNull?.let(DocumentValue::Double)
                    ?: DocumentValue.Null
            }
    }
}

private val layoutShape = DeckDocumentCoding.Shape.Object(mapOf("background_color" to DeckDocumentCoding.Shape.String, "columns" to DeckDocumentCoding.Shape.Integer, "key" to DeckDocumentCoding.Shape.String, "name" to DeckDocumentCoding.Shape.String, "visible" to DeckDocumentCoding.Shape.Boolean))

public fun DeckDocument.Layout.Companion.from(documentEntry: DocumentEntry): DeckDocument.Layout? {
    val fields = documentEntry.fields + ("key" to DocumentValue.String(documentEntry.key))
    return DeckDocumentCoding.decode(fields, serializer<DeckDocument.Layout>())
}

public val DeckDocument.Layout.documentEntry: DocumentEntry
    get() {
        val fields = DeckDocumentCoding.encode(this, serializer<DeckDocument.Layout>(), layoutShape)
        return DocumentEntry(key = key, fields = fields - "key")
    }

private val settingsShape = DeckDocumentCoding.Shape.Object(mapOf("accent_color" to DeckDocumentCoding.Shape.String, "aspect_ratio" to DeckDocumentCoding.Shape.String, "autoplay" to DeckDocumentCoding.Shape.Boolean, "loop_count" to DeckDocumentCoding.Shape.Integer))

public fun DeckDocument.Settings.Companion.from(
    documentFields: Map<String, DocumentValue>,
): DeckDocument.Settings? = DeckDocumentCoding.decode(documentFields, serializer<DeckDocument.Settings>())

public val DeckDocument.Settings.documentFields: Map<String, DocumentValue>
    get() = DeckDocumentCoding.encode(this, serializer<DeckDocument.Settings>(), settingsShape)

private val slideShape = DeckDocumentCoding.Shape.Object(mapOf("duration" to DeckDocumentCoding.Shape.Number, "fit_mode" to DeckDocumentCoding.Shape.String, "key" to DeckDocumentCoding.Shape.String, "layout_key" to DeckDocumentCoding.Shape.String, "opacity" to DeckDocumentCoding.Shape.Number, "start" to DeckDocumentCoding.Shape.Number, "style" to DeckDocumentCoding.Shape.Object(mapOf("fill_color" to DeckDocumentCoding.Shape.String, "shadow_offset" to DeckDocumentCoding.Shape.Object(mapOf("x" to DeckDocumentCoding.Shape.Number, "y" to DeckDocumentCoding.Shape.Number)), "text_decoration" to DeckDocumentCoding.Shape.Array(DeckDocumentCoding.Shape.String)))))

public fun DeckDocument.Slide.Companion.from(documentEntry: DocumentEntry): DeckDocument.Slide? {
    val fields = documentEntry.fields + ("key" to DocumentValue.String(documentEntry.key))
    return DeckDocumentCoding.decode(fields, serializer<DeckDocument.Slide>())
}

public val DeckDocument.Slide.documentEntry: DocumentEntry
    get() {
        val fields = DeckDocumentCoding.encode(this, serializer<DeckDocument.Slide>(), slideShape)
        return DocumentEntry(key = key, fields = fields - "key")
    }

public data class DeckProjection(
    val layouts: List<DocumentEntry> = emptyList(),
    val settings: Map<String, DocumentValue> = emptyMap(),
    val slides: List<DocumentEntry> = emptyList(),
)
/** Refuse a partial typed document: round-tripping it would discard undecodable entries. */
public fun DeckDocument.Companion.from(projection: DeckProjection): DeckDocument? {
    if (projection.layouts.map { it.key }.toSet().size != projection.layouts.size) return null
    val layouts = projection.layouts.map { DeckDocument.Layout.from(it) ?: return null }
    val settings = DeckDocument.Settings.from(projection.settings) ?: return null
    if (projection.slides.map { it.key }.toSet().size != projection.slides.size) return null
    val slides = projection.slides.map { DeckDocument.Slide.from(it) ?: return null }
    return DeckDocument(
        layouts = layouts,
        settings = settings,
        slides = slides,
    )
}

public val DeckDocument.projection: DeckProjection
    get() = DeckProjection(
        layouts = layouts.map { it.documentEntry },
        settings = settings.documentFields,
        slides = slides.map { it.documentEntry },
    )
