# frozen_string_literal: true
require 'json'
require 'net/http'
require 'optparse'
require 'fileutils'
require 'tmpdir'
require 'erb'
require_relative 'manifest'

module ReplicaCodegen
  module CLI
    extend self

    def run(arguments)
      options = {}
      parser = OptionParser.new do |p|
        p.banner = 'replica-codegen --language swift|kotlin|rust --manifest FILE --out DIR [options]'
        %w[language manifest endpoint out document-out ts-out package document-package name config].each do |key|
          p.on("--#{key} VALUE") { options[key.tr('-', '_').to_sym] = it }
        end
        p.on('--check', 'Fail on stale generated output without changing files') { options[:check] = true }
      end
      parser.parse!(arguments)
      raise InvalidManifest, 'unexpected positional arguments' if arguments.any?
      language = options[:language]
      raise InvalidManifest, '--language must be swift, kotlin or rust' unless %w[swift kotlin rust].include?(language)
      raise InvalidManifest, '--out is required' unless options[:out]
      raise InvalidManifest, 'pass exactly one of --manifest / --endpoint' unless [options[:manifest], options[:endpoint]].compact.size == 1
      raise InvalidManifest, '--package is required for Kotlin' if language == 'kotlin' && !options[:package]
      config = options[:config] ? JSON.parse(File.read(options[:config])) : {}
      options[:document_projection] = config.fetch('documentProjection', {})[language]
      if options[:document_projection] && !/\A[A-Za-z_][A-Za-z0-9_.:]*\z/.match?(options[:document_projection])
        raise InvalidManifest, 'invalid document projection type'
      end
      options[:name] ||= config.fetch('name', nil) || 'Replica'
      raise InvalidManifest, 'invalid container name' unless Manifest::IDENTIFIER.match?(options[:name])
      %i[package document_package].each do |key|
        next unless options[key]
        raise InvalidManifest, "invalid #{key}" unless options[key].split('.').all? { Manifest::IDENTIFIER.match?(it) }
      end
      options[:document_package] ||= "#{options[:package]}.documents" if language == 'kotlin'
      raw = if options[:manifest]
        File.read(options[:manifest])
      else
        uri = URI(options[:endpoint])
        raise InvalidManifest, 'endpoint must use HTTP(S)' unless %w[http https].include?(uri.scheme)
        response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https', open_timeout: 10, read_timeout: 30) { it.get(uri.request_uri) }
        raise InvalidManifest, "manifest endpoint answered #{response.code}" unless response.code == '200'
        response.body
      end
      manifest = Manifest.new(JSON.parse(raw), config).compile
      destinations = {}
      Dir.mktmpdir('replicaman-codegen-') do |staging|
        %i[out document_out ts_out].each do |key|
          next unless options[key]
          target = File.expand_path(options[key])
          stage = destinations[target] ||= File.join(staging, destinations.size.to_s)
          options[key] = stage
        end
        # Render and validate every destination before touching existing output.
        Object.include(Naming)
        context = TOPLEVEL_BINDING.dup
        context.local_variable_set(:options, options)
        context.local_variable_set(:manifest, manifest)
        eval(File.read(File.expand_path("../emitters/#{language}.rb", __dir__)), context,
             File.expand_path("../emitters/#{language}.rb", __dir__))
        if language == 'rust' && config.fetch('runtimeCrate', nil)
          raise InvalidManifest, 'invalid runtime crate identifier' unless Manifest::IDENTIFIER.match?(config.fetch('runtimeCrate', nil))
          destinations.each_value do |stage|
            Dir.glob(File.join(stage, '*.rs')).each do |file|
              File.write(file, File.read(file).gsub(/\breplicaman::/, "#{config.fetch('runtimeCrate', nil)}::"))
            end
          end
        end
        destinations.each { |target, stage| install(stage, target, language, check: options[:check]) }
      end
      0
    rescue InvalidManifest, JSON::ParserError, OptionParser::ParseError, SystemCallError => error
      warn "replica-codegen: #{error.message}"
      1
    end

    def install(stage, target, language, check:)
      generated = Dir.glob('*', base: stage).select { File.file?(File.join(stage, it)) }.sort
      ledger = File.join(target, ".replicaman-generated.#{language}.json")
      previous = if File.exist?(ledger)
        JSON.parse(File.read(ledger))
      else
        # First adoption of earlier generated output; never remove handwritten files.
        Dir.glob('*', base: target).select do |name|
          path = File.join(target, name)
          File.file?(path) && File.open(path, &:readline).include?('Generated by replica-codegen')
        rescue EOFError
          false
        end
      end
      raise InvalidManifest, 'invalid generated-file ledger' unless previous.is_a?(Array) && previous.all? { it.is_a?(String) && File.basename(it) == it && it != '.' && it != '..' }
      stale = previous - generated
      changed = generated.reject { File.file?(File.join(target, it)) && File.binread(File.join(target, it)) == File.binread(File.join(stage, it)) }
      if check
        raise InvalidManifest, "stale output in #{target}: #{(stale + changed).join(', ')}" if (stale + changed).any?
        return
      end
      FileUtils.mkdir_p(target)
      changed.each do |name|
        temp = File.join(target, ".#{name}.replicaman-tmp")
        File.binwrite(temp, File.binread(File.join(stage, name)))
        File.rename(temp, File.join(target, name))
      end
      stale.each { File.delete(File.join(target, it)) if File.file?(File.join(target, it)) }
      File.write(ledger, JSON.pretty_generate(generated) + "\n")
    end
  end
end
