#!/usr/bin/env ruby
# Embeds the shared SQLite schema in every client, so no package reads protocol/ at runtime.

ROOT = File.expand_path('..', __dir__)

SOURCES = [
  ['storage.sql', 'ReplicaSyncSchema', 'sync_schema.sql'],
  ['recovery.sql', 'ReplicaRecoverySQL', 'recovery.sql'],
  ['status.sql', 'ReplicaStatusSQL', 'status.sql'],
  ['unsettled.sql', 'ReplicaUnsettledSQL', 'unsettled.sql'],
].freeze

def outputs
  SOURCES.each_with_object({}) do |(source, component, rust_name), files|
    sql = File.read(File.join(ROOT, 'protocol', source)).rstrip
    indented = sql.lines(chomp: true).map { "    #{it}" }.join("\n")
    notice = "// Generated by tools/storage_schema.rb; edit protocol/#{source}.\n"

    files["swift/Sources/ReplicaMan/#{component}.swift"] =
      "#{notice}enum #{component} {\n    static let sql = \"\"\"\n#{indented}\n    \"\"\"\n}\n"
    files["kotlin/libraries/replicaman/src/main/kotlin/io/replicaman/#{component}.kt"] =
      "#{notice}package io.replicaman\n\ninternal object #{component} {\n    val sql: String = \"\"\"\n#{indented}\n    \"\"\".trimIndent()\n}\n"
    files["rust/crates/replicaman/src/#{rust_name}"] = "#{sql}\n"
  end
end

check = ARGV.include?('--check')
stale = outputs.filter_map do |name, text|
  path = File.join(ROOT, name)
  if check
    name unless File.exist?(path) && File.read(path) == text
  else
    File.write(path, text)
    nil
  end
end

abort("Schema copies differ from protocol/: #{stale.join(', ')}") unless stale.empty?
